Feature/86epcnm5q/login generic backoffice
JMSevilla/nclexpower_turbo pull request #126
Opened 2024-06-21 14:10 UTC by JezChristian

2024-06-21 14:27 UTC, JMSevilla requested changes

2024-06-21 14:27 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +  public async backofficeLogin(data: LoginFormType) {
Create a dynamic API call for this, you can pass a string which identifies if which product login should we use. 

like this
return await this.axios.post(
 isWebCustomer ? `` : ``
)

2024-06-21 14:27 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +  public async backofficeLogin(data: LoginFormType) {
Change function name to weblogin

2024-06-21 14:27 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginFormBlock/LoginForm.tsx
> +        <NonCMSTextField control={control} label="Username" name='username' />
Sorry why we are using NonCMSTextField? we can still use our TextField please remove this NonCMSTextField. also delete the implementation we don't need that kind of component

2024-06-21 14:27 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginFormBlock/hooks.ts
> +export const useLogin = () => {
please remove this entire implementation we don't need this since we will be having AuthContext.

2024-06-21 16:24 UTC, JMSevilla requested changes

2024-06-21 16:24 UTC, JMSevilla commented on packages/core-library/components/forms/TextField.tsx
> +        <Typography component="label" htmlFor={field?.name} display="flex">
If im not mistaken this code should be the one implemented

{fieldState?.error?.message ? (
          <FieldError messageKey={fieldState.error.message} />
        )

2024-06-23 04:42 UTC, JMSevilla requested changes

2024-06-23 04:42 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/login.tsx
> +type Props = {
Since we are not using purely dynamic application we can discard this props for now

2024-06-23 04:42 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/login.tsx
> +        login(values.username, values.password, "webBackoffice")
Missing await

2024-06-23 04:42 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/login.tsx
> +        login(values.username, values.password, "webBackoffice")
You shouldn't pass the api parameter here

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +      }, { headers: { ENV: "dev2" } })
If im not mistaken env dev 2 is already included in useApi

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +  public async webLogin(username: string, password: string, type: string) {
You shouldn't define the login params here one by one. It should be props: LoginType

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +      if (err.response?.status === 404) {
Did you look this on the api docs ? i believe we don't have 404 response type from the backend

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +        return { data: null };
What is the purpose of this

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +      throw err;
What is the purpose of this

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/components/forms/TextField.tsx
> +          <FormHelperText error={true}>{fieldState?.error?.message}</FormHelperText>
You shouldn't define the generic boolean value here.

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +interface LoginProps {
You shouldn't define this type inside auth context. Kindly follow the best practices. You can create a global types to feed on the entire login

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +  login(username: string, password: string, type: string): Promise<null>;
You shouldn't pass the api type here this is wrong

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +    } catch (e) { }
Spacing

2024-06-23 04:42 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +            return null
You execute the api then you are return null ?  Please think twice before doing coding

2024-06-23 14:28 UTC, JMSevilla approved these changes

2024-06-23 14:54 UTC, DropitupQwerty approved these changes

2024-06-23 23:49 UTC, acostales08 approved these changes

2024-06-24 10:21 UTC, merged