@86epku02q #Added a report an issue feature, and fix error within cal…
JMSevilla/nclexpower_turbo pull request #128
Opened 2024-06-22 04:58 UTC by be3jaay

…culator UI

2024-06-22 10:08 UTC, JMSevilla requested changes

2024-06-22 10:08 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssueDialog.tsx
> +import React, { useState } from 'react';
Can we just reuse the existing dialog instead of re-creating again.

2024-06-22 10:08 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssueDialog.tsx
> +const ReportSchema = yup.object().shape({
validation should be isolated like the other implementation

2024-06-22 10:08 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssueDialog.tsx
> +const issueCategories: SelectOption[] = [
This mock data should also be isolated

2024-06-23 23:48 UTC, acostales08 approved these changes

2024-06-24 07:20 UTC, JMSevilla requested changes

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +  content: ReactNode;
It should be ReactNode | ReactElement

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +      <DialogContent>
This dialog only accepts text contents? how about if we pass buttons, images etc. then all your content will go within the block of DialogContentText?

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +  title: ReactNode;
When we say title it should be string not reactNode nor React element right ? If you want a title at the same time an icon it should be separate.

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/IssueMockData.ts
> +  { label: 'Bug Problems', value: 'Bug Problems', xvalue: 1 },
I guess we don't need xvalue for this, it should be label and value that's it.

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueDialog.tsx
> +          <form onSubmit={handleSubmit(onSubmit)}>
This can be perform a much cleaner way of code. you can create another function above that returns jsx element and feed that function here.

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueDialog.tsx
> +            <NonCMSTextField
We don't use this anymore. @JezChristian  this component should be delete. 

You can use our existing textfield

2024-06-24 07:20 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueDialog.tsx
> +            <DialogActions>
Based on your implementation, you are now passing a <DialogActions> inside the DialogContentText? this is bad practice.

2024-06-24 07:20 UTC, JMSevilla commented on packages/core-library/components/Textfield/SelectTextfield.tsx
> +  value?: string | string[];
Does adding this type won't effect with the existing implementation ? Kindly coordinate with our developers @acostales08 since we are using this select textfield in simulator.

2024-06-25 11:10 UTC, acostales08 reviewed
move this multipleselectfield.tsx to texfield folder with selectfield

2024-06-25 11:14 UTC, acostales08 commented on packages/core-library/components/MultipleSelectField/SelectMultipleField.tsx
move this multipleselectfield.tsx to texfield folder with selectfield

2024-06-25 11:14 UTC, acostales08 commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueForm.tsx
> +}
avoid using any types

2024-06-25 11:29 UTC, JezChristian commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueForm.tsx
> +import { ControlledMultipleSelectField } from '@repo/core-library/components/MultipleSelectField/SelectMultipleField';
Export the ControlledMultipleSelectField to the index so you don't have to target the specific path

I think ControlledMultipleSelectField is too long to be a name, maybe you can shorten this a little?

2024-06-26 04:32 UTC, JezChristian approved these changes

2024-06-26 07:41 UTC, JMSevilla approved these changes

2024-06-26 08:22 UTC, acostales08 approved these changes

2024-06-26 09:56 UTC, JezChristian approved these changes

2024-06-26 09:56 UTC, DropitupQwerty approved these changes

2024-06-26 10:07 UTC, merged