@86epcnmjw #Creation of reusable header and sidebar. Added drawer layout
JMSevilla/nclexpower_turbo pull request #129
Opened 2024-06-23 11:39 UTC by DropitupQwerty

- Creation of reusable sidebar
- Modify header
- Added Drawer Layout
- Header and sidebar responsiveness

Unauthenticated Header
![image](https://github.com/JMSevilla/nclexpower_turbo/assets/94889927/ad261deb-a961-493e-99ec-6fe3bb0a6b1b)

Authenticated Header and Side Bar
![image](https://github.com/JMSevilla/nclexpower_turbo/assets/94889927/21b9012a-12e7-4bc1-bdb0-1bee40c8b928)

2024-06-23 12:50 UTC, JMSevilla requested changes

2024-06-23 12:50 UTC, JMSevilla commented on packages/core-library/components/GenericDrawerLayout/DrawerLayout.tsx
> +
Too much spacing please use prettier

2024-06-23 12:50 UTC, JMSevilla commented on packages/core-library/components/GenericDrawerLayout/DrawerLayout.tsx
> +const Main = styled('main', {
This can be isolated maybe create a content folder for this?

2024-06-23 12:50 UTC, JMSevilla commented on packages/core-library/components/GenericDrawerLayout/DrawerLayout.tsx
> +            {(isAuthenticated || isMobile) &&
Is this condition intentional for isAuthenticated or isMobile ? I saw this like even if user is unauthorized but if it hits the isMobile it should be truthy?

2024-06-23 12:50 UTC, JMSevilla commented on packages/core-library/components/GenericDrawerLayout/MockMenus.tsx
> +export const mockmenus = (isAuthenticated: boolean) => {
function name should be mockMenus

2024-06-23 12:50 UTC, JMSevilla commented on packages/core-library/components/GenericSidebar/Sidebar.tsx
> +type SideBarPropsType = {
Got multiple types defined here, isolate some.

2024-06-23 23:47 UTC, acostales08 approved these changes

2024-06-24 10:33 UTC, DropitupQwerty commented on packages/core-library/components/GenericDrawerLayout/DrawerLayout.tsx
> +            {(isAuthenticated || isMobile) &&
Yes Sir. I made this condition so that unauthorized user can use the sidebar in mobile view for responsiveness

2024-06-24 14:11 UTC, JMSevilla approved these changes

2024-06-24 14:24 UTC, JezChristian approved these changes

2024-06-24 15:14 UTC, be3jaay approved these changes

2024-06-24 15:20 UTC, merged