@feature/86epku5nr/AccessToken-Validation
JMSevilla/nclexpower_turbo pull request #132
Opened 2024-06-24 18:57 UTC by acostales08

2024-06-25 08:06 UTC, JMSevilla requested changes

2024-06-25 08:06 UTC, JMSevilla commented on apps/simulator/src/core/context/AppContext.tsx
> +  const [hasAccessToken, setHasAccessToken] = useState<boolean>(false);
Actually we don't need this hasAccessToken thing anymore since we are directly accessing the accessToken unless this is going to be used in other code?

2024-06-25 08:06 UTC, JMSevilla commented on apps/simulator/src/core/context/AppContext.tsx
> +    console.log('loadPTestHimemCb', loadPTestHimemCb.result?.status);
remove console logs

2024-06-25 08:06 UTC, JMSevilla commented on apps/simulator/src/core/context/AppContext.tsx
> +    if (!accessToken) {
Transfer this to different useEffect and add accessToken as dependency

2024-06-25 08:06 UTC, JMSevilla commented on packages/core-library/cms-initialization.ts
> +    `${config.value.API_URL}/v1/api/baseAppload/processor-load-ptest-himem`,
Revert the code back to ApiUrl

2024-06-25 08:06 UTC, JMSevilla commented on apps/simulator/src/core/context/AppContext.tsx
> +    hasAccessToken && selectQuestionCb.execute({ ...questionData });
You can directly use accessToken here for conditional to check it immediately

2024-06-25 08:06 UTC, JMSevilla commented on apps/simulator/src/core/context/AppContext.tsx
> +  }, [questionData, selectQuestionCb, hasAccessToken]);
Change the dependency to accessToken

2024-06-25 11:48 UTC, acostales08 commented on apps/simulator/src/core/context/AppContext.tsx
> +  const [hasAccessToken, setHasAccessToken] = useState<boolean>(false);
i retain this state since i used it in layout

2024-06-25 15:16 UTC, DropitupQwerty approved these changes

2024-06-26 02:41 UTC, JMSevilla approved these changes

2024-06-26 04:25 UTC, JezChristian approved these changes

2024-06-26 05:09 UTC, be3jaay approved these changes

2024-06-26 06:32 UTC, merged