@86epmb28q Added Detection Access Token and Added customizable style …
JMSevilla/nclexpower_turbo pull request #135
Opened 2024-06-27 14:27 UTC by be3jaay

…in custom dialog.

2024-06-27 14:33 UTC, JezChristian commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +  dialogSx?: object;
Consider changing this, we don't really use object as the type as is,  try making it more defined

2024-06-27 16:02 UTC, JezChristian approved these changes

2024-06-27 17:03 UTC, DropitupQwerty approved these changes

2024-06-28 02:39 UTC, JMSevilla requested changes

2024-06-28 02:39 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +  sx?: {
This is miscommunication. This code shouldn't be an object please remove all the properties inside this object and permanently removed it. 

sx?: DialogProps['sx']

2024-06-28 02:39 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueDialog.tsx
>  export interface FormValues {
This is also bad practice. This is an interface a pure typescript but you are adding a JSX code inside of it.

2024-06-28 02:39 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/ReportIssue/ReportIssueDialog.tsx
> +        sx={{
We shouldn't add directly this styles inside an interface which is identified as pure typescript.

2024-06-28 02:39 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +    <Dialog open={open} aria-labelledby="custom-dialog-title" sx={sx.dialog}>
I suggest to not use sx if you want to create a multiple styles in your dialog. you can use the styled function from MUI system to make it more readable and easy to maintain. example : 

const CustomDialog = styled(Dialog)(({ theme }) => ({
  // your styles here
}));

const CustomDialogContent = styled(DialogContent)(({ theme }) => ({
  // your styles here
}));

2024-06-28 08:58 UTC, JMSevilla requested changes

2024-06-28 08:58 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +const DefaultDialog = styled(Dialog)(({ theme }) => ({
We don't want to add empty code as part of best practices if needed then we can just add it here.

2024-06-28 08:58 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
> +const DefaultDialogContent = styled(DialogContent)(({ theme }) => ({
Same here

2024-06-28 09:11 UTC, acostales08 approved these changes

2024-06-28 09:28 UTC, JMSevilla approved these changes

2024-06-28 09:31 UTC, merged