Feature/86epp79gb data grid integration modal for IRT's
JMSevilla/nclexpower_turbo pull request #141
Opened 2024-06-29 17:28 UTC by LizterBabael

2024-06-29 17:58 UTC, be3jaay requested changes

2024-06-29 17:58 UTC, be3jaay commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +            <TableIRTExamLogs title="IRT-EXAM-LOG" />
Bad Practice: Don't add JSX code inside an interface.

2024-06-29 17:58 UTC, be3jaay commented on apps/simulator/src/components/Dialog/IRT's/ThetaZero/ThetaZeroComp.tsx
> +  title?: string;
You're repeating the same props, maybe create one prop then pass it instead of creating it again.

2024-06-29 18:52 UTC, DropitupQwerty commented on apps/simulator/src/core/constant/IRTsMockData.ts
isolate datatypes in another files

2024-06-30 02:24 UTC, JMSevilla requested changes

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/ExamLogs/TableIRTLogs.tsx
> +import { DataGrid } from '@repo/core-library/components';
Your folder name is not valid we don't need to create a file/folder with '

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +  useEffect(() => {
Instead of using this manual code from JS for click away event you can use 
ClickAwayListener from MUI

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
>  export const CustomDialog: React.FC<CustomDialogProps> = ({
@be3jaay I didn't noticed you are not using React.PropsWithChildren instead you are passing children react node in props. You can use React.PropsWithChildren<CustomDialogProps> so you can remove the children from the props

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +            <TableIRTExamLogs title="IRT-EXAM-LOG" />
I guess this is fine, I thought @LizterBabael adds JSX code inside an pure typescript code but based on this changes content is expecting to have ReactNode right?

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +            <TableIRTExamLogs title="IRT-EXAM-LOG" />
@LizterBabael There is much more cleaner way to do this. You can create a function like 

const ThetaTableTestMode = () => (
 <React.Fragment>
... your data grids here.
</React.Fragment>
)

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +        button={
@be3jaay  @LizterBabael  What is the difference between the button with function of handleClose and the onClose property? 

I've noticed you are passing 2 handleClose at the same time. This should be fix

2024-06-30 02:24 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/IRT's/ThetaComputation/ThetaCompScratch.tsx
> +export const ThetaCompScratch: React.FC<Props> = ({ title }) => {
I've also noticed that you created multiple implementation with the same approach. Can you just reuse all of those in one implementation ?

2024-06-30 02:30 UTC, be3jaay commented on apps/simulator/src/components/Dialog/CustomDialog.tsx
>  export const CustomDialog: React.FC<CustomDialogProps> = ({
@JMSevilla Should I include this within my pr, or Lizter will do the work?

2024-06-30 02:37 UTC, be3jaay commented on apps/simulator/src/components/Dialog/IRT's/IRTModal.tsx
> +        button={
I think Lizter explained to me yesterday that he is implementing two handleClose: one for manually closing within the form and the other for event key 'ESC' onClose.

2024-06-30 13:15 UTC, JMSevilla approved these changes

2024-06-30 13:17 UTC, be3jaay approved these changes

2024-06-30 13:50 UTC, JezChristian approved these changes

2024-06-30 13:53 UTC, acostales08 approved these changes

2024-06-30 13:55 UTC, merged