@86epkjffc #Web Customer Homepage w/ Generic Footer
JMSevilla/nclexpower_turbo pull request #152
Opened 2024-07-02 17:35 UTC by JezChristian

2024-07-02 18:45 UTC, DropitupQwerty commented on apps/web-customer/src/components/CustomerFooter/Footer.tsx
> +const lists = [
isolate mock data to a different folder

2024-07-02 18:50 UTC, DropitupQwerty commented on apps/web-customer/src/components/CustomerHeader/Header.tsx
> +    const headerList = [
isolate this list

2024-07-02 18:50 UTC, DropitupQwerty commented on apps/web-customer/src/components/CustomerHeader/Header.tsx
> +                        <button className="text-white">{item.label}</button>
add key to this button

2024-07-02 18:54 UTC, DropitupQwerty commented on apps/web-customer/src/pages/contents/HomePage/CoreZigmaSystem/CoreZigma.tsx
> +const FlipCard: React.FC<FlipCardProps> = ({ frontImage, backImage }: any) => {
you can remove the any type . you already have datatypes

2024-07-02 19:07 UTC, DropitupQwerty commented on apps/web-customer/src/pages/index.tsx
> +import { RevolutionBanner } from '@/pages/contents/HomePage/RevolutionBanner/RevolutionBanner';
directly accessing the RevolutionBanner

2024-07-02 19:23 UTC, DropitupQwerty commented on apps/web-customer/src/pages/index.tsx
> +import { RevolutionBanner } from '@/pages/contents/HomePage/RevolutionBanner/RevolutionBanner';
Directly accessing the components

2024-07-02 19:26 UTC, DropitupQwerty commented on apps/web-customer/src/pages/contents/HomePage/index.ts
> +export * as CoreZigma from './CoreZigmaSystem/CoreZigma'
remove "as ComponentName" so you can access the component without error

export  * from './directory/file'

2024-07-02 19:29 UTC, DropitupQwerty commented on apps/web-customer/src/components/CustomerFooter/Footer.tsx
> +// import CoreZigma from '@repo/core-library/components/Header/asset/CoreZigma.png'
remove comments

2024-07-03 02:26 UTC, JMSevilla requested changes

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerFooter/Footer.tsx
> +export const Footer = () => {
Can we just create a footer component that can be reuse all over our products?

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerFooter/Footer.tsx
> +export const Footer = () => {
Content of this footer should be coming from the interface Props {} for future use.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerFooter/Footer.tsx
> +            <p className='w-full text-center pt-4'>© 2024 NCLEXPower ™. All rights reserved.</p>
You can use javascript function like `new Date().getFullYear())` so it won't be written generically.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerHeader/Header.tsx
> +export const Header = () => {
Can we make this reusable for unauthorized and authorized users ? when using react we should take advantage of using reusable components.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerHeader/Header.tsx
> +    useEffect(() => {
can we use our `useScroll` hook to achieve what you want here? please just replace the imported router to `next/router`

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/SliderComponent.tsx
> +import NCLEXLogo from '../assets/NCLEXPowerLogo.png'
This is messy. Can we centralized all the assets imports?

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/SliderComponent.tsx
> +import "slick-carousel/slick/slick.css";
This third-part library imports should be on the higher level of our code.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/SliderComponent.tsx
> +
Spacing

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/components/SliderComponent.tsx
> +    const settings = {
This can be pass dynamically you can add interface Props {}

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/_app.tsx
> +      <Header />
What is in your mind why you put the header here? how can we able to dismantle this code when user is authorized since our AuthContext is inside the Page.tsx?

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/_app.tsx
> +      <Footer />
Also this one. You are not build a single page for this project always think what will be the impact of this when we have a user using login and stuff.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/CoreZigmaSystem/CoreZigma.tsx
> +// import CoreZigmaLogo from '@repo/core-library/components/Header/asset/CoreZigma.png'
Unused imports a basic best practices you can follow.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/CoreZigmaSystem/CoreZigma.tsx
> +import FlipCardOne from '../../../../assets/Flip1Front.png'
A messy kind of code imports for our assets.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/CoreZigmaSystem/CoreZigma.tsx
> +const FlipCard: React.FC<FlipCardProps> = ({ frontImage, backImage }: any) => {
This flip card component can also be a reusable component

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/CoreZigmaSystem/CoreZigma.tsx
> +export const CoreZigma = () => {
This also needs to have interface Props {}

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/HowItWorks/HowItWorks.tsx
> +const FlipCard: React.FC<CardProps> = ({ title }) => {
I've noticed you've been using this multiple times you can create a reusable component for this.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/HowItWorks/HowItWorks.tsx
> +export const HowItWorks = () => {
This needs to also have interface Props {} you should prepare your component, pages for reusability.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/Pricing/Pricing.tsx
> +    const isGreen = nurseType === 0;
Prevent unecessary re-renders 

// More descriptive variable names
    const isNurseTypeStandard = nurseType === 0;
    const isCardTypePrimary = type === 1;

    // Memoize values to avoid unnecessary calculations on re-renders
    const isGreen = useMemo(() => isNurseTypeStandard, [nurseType]);
    const isTypeOne = useMemo(() => isCardTypePrimary, [type]);

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/contents/HomePage/Pricing/Pricing.tsx
> +export const Pricing = () => {
The implementation is too generic improve this code for a better. some AI out there can help you to make this better.

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/index.tsx
> +import { RevolutionBanner } from '@/pages/contents/HomePage/RevolutionBanner/RevolutionBanner';
You can centralized all the imports like import { ...all your contents }

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/index.tsx
> +        <RevolutionBanner />
The naming convention for this I suggest to be -> <RevolutionBannerBlocks />

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/index.tsx
> +        <CoreZigma />
The naming convention for this I suggest to be -> <CoreZigmaBlocks />

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/index.tsx
> +        <HowItWorks />
The naming convention for this I suggest to be -> <HowItWorksBlocks  />

2024-07-03 02:26 UTC, JMSevilla commented on apps/web-customer/src/pages/index.tsx
> +        <Pricing />
The naming convention for this I suggest to be -> <PricingBlocks />

2024-07-03 03:24 UTC, JezChristian commented on apps/web-customer/src/pages/_app.tsx
> +      <Header />
I assumed that Header and Footer should be displayed in all pages

2024-07-04 17:14 UTC, DropitupQwerty approved these changes

2024-07-04 18:08 UTC, acostales08 approved these changes

2024-07-05 08:35 UTC, JMSevilla requested changes

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/dashboard.tsx
> +const Card = ({ textColor, bgColor, title, cardValue }: CardProps) => {
This is identified as reusable component. Also just you know i have also developed a card component so in the future this will be change

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/CustomCard/CustomCard.tsx
> +export const CustomCard: React.FC<CardProps> = ({ title }) => {
You created a CustomCard but you still define const Card = () => {} above

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/CustomerHeader/Header.tsx
> +export const Header: React.FC<Props> = ({ menu }) => {
@DropitupQwerty The DRY procedure is being seen. Can we reuse our existing header instead of creating another one?

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/FlippableCard/FlipCard.tsx
> +export const FlipCard: React.FC<FlipCardProps> = ({ frontImage, backImage }) => {
Another Card component , we can use 1 Card to address all the requirements i believe.

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/ReactSlider/SliderComponent.tsx
> +} from '../../../../../packages/core-library/globalAssets'
import strategy can be 'core-library' and can you please rename it from globalAssets to just `assets`

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/ReactSlider/SliderComponent.tsx
> +            <Slider {...sliderConfig}>
I believe we can create a reusable component for Slider from core-library to prevent this Slider library from being imported repeatedly

2024-07-05 08:35 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HomePageBlocks/HowItWorks/HowItWorksBlock.tsx
> +
Spacing

2024-07-05 08:35 UTC, JMSevilla commented on packages/core-library/components/ReusableFooter/Footer.tsx
> +export const Footer: React.FC<FooterProps> = (props) => {
Can we reuse or existing footer?

2024-07-05 10:04 UTC, JezChristian commented on apps/web-backoffice-generic/src/pages/dashboard.tsx
> +const Card = ({ textColor, bgColor, title, cardValue }: CardProps) => {
Ay nadamay lang po sa commit yan sir, pero di pa po yan tapos talaga, next ticket ko pa po kasi yan.

2024-07-08 03:37 UTC, JMSevilla approved these changes

2024-07-08 10:01 UTC, merged