@feature/86eppzzee/Tabs_for_regQuestion_and_CStudy
JMSevilla/nclexpower_turbo pull request #159
Opened 2024-07-04 18:19 UTC by acostales08

2024-07-05 06:54 UTC, JezChristian commented on apps/web-backoffice-generic/src/pages/manageQuestionaire.tsx
> +          tabValue === 1 && <CaseStudyQustionaire />
If you only have 2 expected output which is RegQuestionnaire and CaseStudyQuestionnaire

I think you dont need the tabValue === 1 && in your else block?

2024-07-05 06:57 UTC, JezChristian commented on packages/core-library/components/Tabs/tab.tsx
> +          {tabsName.map((item: tabsNameProps, index: number) => (
add tabsName.length > 0 && tabsName.map

2024-07-05 06:58 UTC, JezChristian commented on apps/web-backoffice-generic/src/components/blocks/caseStudyQustionaire.tsx
> +export const CaseStudyQustionaire = () => {
the name is in wrong spelling

2024-07-05 06:59 UTC, JezChristian commented on apps/web-backoffice-generic/src/components/blocks/regQuestionaire.tsx
> +export const RegQuestionaire = () => {
double "n" in Questionnaire

2024-07-05 07:02 UTC, JezChristian commented on packages/core-library/components/GenericDrawerLayout/MockMenus.tsx
> +import { NavigationType } from "../../types/navigation";
Just a question, is it not possible to import them all from a single "@mui/icons-material" ?

2024-07-05 08:41 UTC, JMSevilla requested changes

2024-07-05 08:41 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/manageQuestionaire.tsx
> +import React, { useState } from "react";
Your filename will be consider as route are you sure you will name this as `manageQuestionaire` ? imagine `/hub/manageQuestionnaire` is this weird?

2024-07-05 08:41 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/manageQuestionaire.tsx
> +      <ControlledTabs
If i'm not mistaken this is copied from my repository, we can improve our tab components not on this way.

2024-07-06 10:13 UTC, JMSevilla approved these changes

2024-07-06 10:14 UTC, DropitupQwerty approved these changes

2024-07-06 10:15 UTC, LizterBabael approved these changes

2024-07-06 10:15 UTC, merged