@86epq019c #ForgotPassword Page UI
JMSevilla/nclexpower_turbo pull request #160
Opened 2024-07-05 19:54 UTC by LizterBabael

2024-07-06 08:37 UTC, be3jaay commented on apps/web-customer/src/core/Schema/ForgotPasswordValidation.ts
> +  email: yup.string().required("Email is required").default(""),
should be email

2024-07-06 08:37 UTC, be3jaay commented on apps/web-customer/src/pages/ForgotPassword.tsx
> +export const ForgotPasswordPage = () => {
should be similar to the file name.

2024-07-06 08:42 UTC, be3jaay approved these changes

2024-07-06 11:30 UTC, DropitupQwerty commented on apps/web-customer/src/components/blocks/ForgotPasaswordBlock/ForgotPasswordBlock.tsx
> +  const form = useForm({
Move this inside the block

2024-07-06 13:05 UTC, JezChristian approved these changes

2024-07-06 19:42 UTC, acostales08 approved these changes

2024-07-08 02:46 UTC, JMSevilla requested changes
This implementation is not aligned with our current system diagram.

2024-07-08 14:40 UTC, JMSevilla approved these changes

2024-07-08 19:00 UTC, merged