@86epnyz6q #Change-Password-Page-UI
JMSevilla/nclexpower_turbo pull request #183
Opened 2024-07-11 00:04 UTC by LizterBabael

Modify folder structure for ForgotPassword validation
Added isLoading props on ForgotPassword
Created Change Password Page UI
Created validation for all fields

2024-07-11 03:56 UTC, JMSevilla requested changes

2024-07-11 03:56 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ChangePasswordForm.tsx
> +                      <TextField
This is unacceptable. why we are not using our own textfield ? you are setting the value manually.

2024-07-11 03:56 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ChangePasswordForm.tsx
> +                        <Checkbox
We also have a reusable checkbox why we can't use that?

2024-07-11 03:56 UTC, JMSevilla commented on apps/web-customer/src/core/Schema/ChangePasswordForm/validation.ts
> +      /^(?=.*[0-9])(?=.*[A-Z]).{6,}$/,
Good thing that we have regex. but please create a specific file in core-library to isolate all our regex 

create a file named -> `regex.ts`

2024-07-11 03:56 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ChangePasswordBlock.tsx
> +    <ChangePasswordForm
Since you are manually passing all the dependencies for your change password form this is considered as prop drilling

2024-07-12 06:44 UTC, be3jaay approved these changes

2024-07-12 11:33 UTC, JMSevilla requested changes

2024-07-12 11:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ChangePasswordForm.tsx
> +
spacing

2024-07-12 11:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ShowPassword.ts
> +export const useShowPasswordForm = () => {
This is a hook but your filename is `ShowPassword` it should be `useShowPassword` this is much better instead of `useShowPasswordForm`

1 thing is this hook can reuse to our other applications or not?

2024-07-12 11:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ValidationIndicator.tsx
> +interface ValidationChecks {
Why did you create another interface if you will add all of this to another interface which is `Props` ? 

you can transfer all your boolean data types directly inside the `Props`

2024-07-12 11:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ValidationIndicator.tsx
> +export const ValidationIndicators = ({ validationChecks }: Props) => {
You should ask first to backend developer what is our password requirements before declaring the password strictness to your UI. this will create another dev work if missed.

2024-07-12 11:33 UTC, JMSevilla commented on packages/core-library/types/regex.ts
> +export const validatePassword = (password: any) => {
Your code is not complimenting with the file name. the file says it is regex but you write a schema validation here. 

For validations please make sure to put it together with your blocks and name it `validation.ts`

2024-07-12 11:33 UTC, JMSevilla commented on packages/core-library/types/regex.ts
> +export const validatePassword = (password: any) => {
We are not using any data types.

2024-07-12 20:18 UTC, LizterBabael commented on apps/web-customer/src/components/blocks/ChangePasswordBlock/ChangePasswordForm.tsx
> +
my IDE autoformatted it when i saved my changes.

2024-07-13 10:26 UTC, JMSevilla requested changes

2024-07-13 10:26 UTC, JMSevilla commented on packages/core-library/utils/Regex.ts
> +});
You should just add all the regex constants here not functions

2024-07-13 12:33 UTC, JezChristian approved these changes

2024-07-13 12:33 UTC, acostales08 approved these changes

2024-07-13 12:36 UTC, JMSevilla approved these changes

2024-07-13 12:38 UTC, merged