Feature/86epu3gf5/logout button
JMSevilla/nclexpower_turbo pull request #195
Opened 2024-07-14 18:07 UTC by JezChristian

Reusable Dropdown
Logout Dropdown Relocation

2024-07-14 19:04 UTC, LizterBabael approved these changes

2024-07-15 10:58 UTC, JMSevilla requested changes

2024-07-15 10:58 UTC, JMSevilla commented on packages/core-library/components/GenericDropDown/DropDown.tsx
> +                    {list.length > 0 && list.map((item, index) => (
I see that you use mapping to make the list dynamic. but did you consider when we have its functionality ? it should be dynamic too right.

2024-07-15 10:58 UTC, JMSevilla commented on packages/core-library/components/GenericDropDown/MockDropDownMenu.tsx
> +export const DropDownMenu: NavigationType[] = [
All utilization must be placed within the project core folder.

2024-07-15 13:30 UTC, acostales08 approved these changes

2024-07-15 16:21 UTC, DropitupQwerty approved these changes

2024-07-16 08:21 UTC, JMSevilla requested changes

2024-07-16 08:21 UTC, JMSevilla commented on apps/web-backoffice-generic/src/core/constant/UserDropDown.tsx
> +        onClick: handleLogout
@JezChristian we can't also accept this. imagine if we store this on our DB.

2024-07-16 14:41 UTC, JMSevilla requested changes

2024-07-16 14:41 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/shared/Layout.tsx
> +  const onLogout = () => { console.log("LOGOUT") }
What i mean by this is that you should use our existing logout from useAuthContext.

2024-07-16 15:01 UTC, JMSevilla approved these changes

2024-07-16 15:29 UTC, merged