@86epzggjz # Pricing-Page Dynamic Details
JMSevilla/nclexpower_turbo pull request #206
Opened 2024-08-07 17:35 UTC by JezChristian

Changes:
- Added (RN) and (PN) in order summary as per request of Client
- Dynamic Data in Payment Checkout

2024-08-07 18:51 UTC, JMSevilla requested changes

2024-08-07 18:51 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/OrderCheckoutBlock/OrderCheckoutBlock.tsx
> +    console.log("orderNumber : ", orderNumber)
remove console logs

2024-08-08 14:30 UTC, JMSevilla approved these changes

2024-08-08 16:05 UTC, DropitupQwerty approved these changes

2024-08-08 16:05 UTC, acostales08 approved these changes

2024-08-09 06:22 UTC, LizterBabael approved these changes

2024-08-09 11:26 UTC, merged