Feature/86eppzyvv/create regular question
JMSevilla/nclexpower_turbo pull request #215
Opened 2024-08-13 12:11 UTC by JezChristian

2024-08-20 16:56 UTC, JMSevilla requested changes

2024-08-20 16:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/validation.ts
> +export const regularSATAAnswersSchema = yup.object({
Redundant schema for answer and answerKey

2024-08-20 16:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/steps/content/useRegularQuestionForm.tsx
> +  const form = useForm<RegularQuestionsFormType>({
We can just use 1 useForm here

2024-08-20 16:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/steps/content/useRegularQuestionForm.tsx
> +  regularQuestionsFormSchema,
We shouldn't use any schema aside from our contained schema

2024-08-20 16:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/AnswerOptions/blocks/SATA/SATA.tsx
> +import { Button, Card, ControlledCheckbox } from "core-library/components";
Instead of creating isolated answer options why not create a AnswerOptionSataBlock and AnswerOptionsMcqBlock we can both render these in a certain code wherein we can use switch casing ?

2024-08-21 07:54 UTC, JMSevilla approved these changes

2024-08-21 07:58 UTC, BryanPalad approved these changes

2024-08-21 08:01 UTC, be3jaay approved these changes

2024-08-21 08:18 UTC, merged