@86epxqzpe #Step 4 Reusable Success Page
JMSevilla/nclexpower_turbo pull request #227
Opened 2024-08-18 17:36 UTC by JezChristian

2024-08-18 17:46 UTC, JMSevilla requested changes

2024-08-18 17:46 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/ChooseQuestionType.tsx
> +import { SuccessPage } from '../../../../../../blocks/page';
It is fine to use @/components here we just changed what we have in your test file.

2024-08-18 17:56 UTC, JMSevilla requested changes

2024-08-18 17:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/steps/content/SuccessPage.tsx
> +// import { ContainedRegularQuestionType } from '@/components/blocks/page/SettingsManagement/steps/content/simulator/types';
Comments

2024-08-18 17:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/SettingsManagement/steps/content/simulator/steps/content/SuccessPage.tsx
> +        <div data-testid={values.main_type} className='h-[650px] flex flex-col items-center justify-center p-5 gap-y-10'>
This isn't the best practices we should implement by using data-testid. `values.main_type` potentially has upperCasing

example suggestion: data-testid={`${dynamicDataExample}-question`}

2024-08-18 17:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/tests/SuccessPage.test.tsx
> +(useRouter as jest.Mock).mockReturnValue({
Why we aren't using this? 

jest.mock("../../../core/router", () => ({
  useRouter: jest.fn(),
}));

2024-08-18 17:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/tests/SuccessPage.test.tsx
> +    it('Should Display Success Page for Regular Question', () => {
Please make some reference on our existing test. you should use smaller case when writing description on each test cases. 
`should render success page for regular question`

2024-08-18 17:56 UTC, JMSevilla commented on apps/web-backoffice-generic/src/tests/SuccessPage.test.tsx
> +    it('Go to Regular Question List', () => {
Always add `should`.

`it go to ? ` or `it should go to regular question list?`

2024-08-19 00:53 UTC, EderDM approved these changes

2024-08-19 02:56 UTC, be3jaay commented on apps/web-backoffice-generic/src/tests/SuccessPage.test.tsx
> +    it('it should display success page for regular question', () => {
I believe there's no need to include "it" twice, as it might make the sentence sound redundant. 
For example: `it('should display success page for regular question')

2024-08-19 08:55 UTC, JMSevilla approved these changes

2024-08-19 09:48 UTC, LizterBabael approved these changes

2024-08-19 12:03 UTC, merged