@86eq1kv7j #Pricing Block Bug Fixes
JMSevilla/nclexpower_turbo pull request #228
Opened 2024-08-19 00:03 UTC by JezChristian

2024-08-19 00:53 UTC, EderDM approved these changes

2024-08-19 04:08 UTC, JMSevilla requested changes

2024-08-19 04:08 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HomePageBlocks/Pricing/PricingComponent/PricingCard.tsx
> +            onClick={() =>
This is prop drilling. I suggest to create a separate function instead.

2024-08-19 10:59 UTC, LizterBabael approved these changes

2024-08-19 11:51 UTC, DropitupQwerty approved these changes

2024-08-20 11:16 UTC, BryanPalad approved these changes

2024-08-20 11:45 UTC, be3jaay approved these changes

2024-08-20 16:44 UTC, JMSevilla approved these changes

2024-08-20 16:45 UTC, merged