@86epq04wa #Create user internal account
JMSevilla/nclexpower_turbo pull request #242
Opened 2024-08-24 11:33 UTC by be3jaay

2024-08-26 13:47 UTC, JMSevilla requested changes

2024-08-26 13:47 UTC, JMSevilla commented on packages/core-library/api/web/web-api.ts
> +    return this.axios.post<number>(
When creating a user and throwing user data we should consider using SSR

2024-08-26 13:47 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +          createInternalAccount: async (data: internalAccountType) => {
I guess we can use register function from authContext

2024-08-27 15:41 UTC, JezChristian approved these changes

2024-08-28 04:29 UTC, JMSevilla requested changes

2024-08-28 04:29 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +            if (data.appName === "webdev_app") {
Instead of adding this appName on your schema why not we use our config ? do we even use the appName as payload to our API ?

2024-08-28 04:29 UTC, JMSevilla commented on packages/core-library/contexts/auth/AuthContext.tsx
> +            } else {
Based on your condition if the statement is not satisfied then it will fall by default in `internalAccountCb` This can lead to a security issue in the future. 

Since we are not using `register` function in WC just do `if (config.value.BASEAPP === 'webdev_app')` You just need 1 condition for this logic.

2024-08-28 12:42 UTC, LizterBabael approved these changes

2024-08-28 15:14 UTC, DropitupQwerty approved these changes

2024-08-29 10:12 UTC, JMSevilla approved these changes

2024-08-29 10:14 UTC, merged