@86epxqyub #Create regular question step 2 and validation
JMSevilla/nclexpower_turbo pull request #250
Opened 2024-08-28 00:42 UTC by DropitupQwerty

2024-08-28 04:58 UTC, DropitupQwerty commented on packages/core-library/components/Radio/Radio.tsx
> +
Spacing

2024-08-28 04:58 UTC, DropitupQwerty commented on packages/core-library/components/Radio/Radio.tsx
> +
Spacijg

2024-08-28 05:00 UTC, DropitupQwerty commented on packages/core-library/components/blocks/AnswerOptions/blocks/SATA/SATA.tsx
>  import { ControlledTextField } from "../../../../Textfield/TextField";
Should use absolute importing

2024-08-28 05:01 UTC, DropitupQwerty commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/constants/constants.ts
> +
Spacing

2024-08-29 18:58 UTC, JezChristian approved these changes

2024-08-29 18:59 UTC, JezChristian commented
Code Cov Build Failure

2024-08-30 18:02 UTC, acostales08 approved these changes

2024-08-30 19:16 UTC, JezChristian reviewed
More on spacing , kindly remove the unnecessary spacing, Thank you!

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
> +import { ControlledRadio, Card } from '../../../../';
To lessen the lines, maybe you can merge the import of ControlledTextField , ControlledRadio and Card

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
> +import { ControlledRadio, Card } from '../../../../';
And the path somehow feels wrong to be "../../../../"

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/AnswerOptions.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/AnswerOptions.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/AnswerOptions.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
> +
spacing

2024-08-30 19:16 UTC, JezChristian commented on packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
> +
spacing

2024-08-30 19:24 UTC, DropitupQwerty commented on packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
> +import { ControlledRadio, Card } from '../../../../';
Having a build build failure when yung using core-library import

2024-08-30 20:38 UTC, JMSevilla commented on packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
> +import { ControlledRadio, Card } from '../../../../';
We can accept this for now

2024-08-30 20:53 UTC, JMSevilla requested changes

2024-08-30 20:53 UTC, JMSevilla commented on packages/core-library/components/blocks/AnswerOptions/blocks/MCQ/MCQ.tsx
> +          {Array.from({ length: 4 }).map((_, index) => (
Suggestion for this

declare constant
const NUMBER_OF_OPTIONS = 4;

then > Array.from({ length: NUMBER_OF_OPTIONS }).map((_, index) =>

2024-08-30 20:53 UTC, JMSevilla commented on packages/core-library/tests/components/Blocks/AnswerOptions/blocks/SATA.test.tsx
> +import { getAllByRole, render, waitFor } from '@testing-library/react';
We should still use this imports from our commons

2024-08-31 10:00 UTC, BryanPalad approved these changes

2024-08-31 13:51 UTC, JMSevilla approved these changes

2024-08-31 13:53 UTC, merged