Feature/86epxqymx/reusable accordion integration with mapping from atom
JMSevilla/nclexpower_turbo pull request #251
Opened 2024-08-28 14:45 UTC by acostales08

-Reusable accordion integration with mapping from atom
-Create Regular Question and Answer Summary Page UI
-Integration of Information Alert Notification Message
-Continue Button
-Integration Confirmation Modal before Insertion

2024-08-28 15:15 UTC, DropitupQwerty commented on packages/core-library/components/blocks/Accordion/SummaryAccordion.tsx
> +export const SummaryAccordion: React.FC<Props> = ({ item, type, index }) => {
Isolate some of the components

2024-08-29 03:12 UTC, DropitupQwerty commented on packages/core-library/components/blocks/Accordion/SummaryAccordion.tsx
> +interface ContentProps {
Too many type in a single file

2024-08-29 03:12 UTC, DropitupQwerty commented on packages/core-library/components/blocks/Accordion/SummaryAccordion.tsx
> +const AnswerOptionContent: React.FC<AnswerOptionContentProps> = (props) => {
Can you seperate this in another folder?

2024-08-29 03:15 UTC, DropitupQwerty commented on packages/core-library/tests/page/SummaryAccordion.test.tsx
> +import "@testing-library/jest-dom";
I think you remove this import

2024-08-29 03:16 UTC, DropitupQwerty commented on packages/core-library/tests/page/SummaryAccordion.test.tsx
> +// Mocking necessary dependencies
remove comments

2024-08-29 03:18 UTC, DropitupQwerty commented on packages/core-library/tests/page/QuestionSummary.test.tsx
> +// import { render, screen, fireEvent } from "@testing-library/react";
remove comments

2024-08-29 03:20 UTC, DropitupQwerty commented on packages/core-library/components/Dialog/DialogFormBlocks/RegularQuestion/ConfirmationDialog.tsx
> +import { ContainedRegularQuestionType } from "../../../../system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/types"; // Ensure this import path is correct
Remove comments

2024-08-30 15:39 UTC, JMSevilla requested changes

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/components/blocks/Accordion/SummaryAccordionContent.tsx
> +interface SummaryAccordionContentProps extends ContentProps {
Can we use this instead

interface SummaryAccordionContentProps extends ContentProps {
  type: "SATA" | "MCQ"; // Union type for type safety
}

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/components/blocks/Accordion/SummaryAccordionContent.tsx
> +  const renderType = (type: string, answerKey: boolean) => {
Put your renderType in `useCallback`

const renderType = useCallback((type: "SATA" | "MCQ", answerKey: boolean) => {
    switch (type) {
      case "SATA":
        return <Checkbox disabled checked={answerKey} aria-label="Selected SATA answer" />;
      case "MCQ":
        return <Radio disabled checked={answerKey} aria-label="Selected MCQ answer" />;
      default:
        return null;
    }
  }, []);

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/components/blocks/Accordion/SummaryAccordionContent.tsx
> +        <Box
For code improvement and to prevent style repetition 

use this

const MainBox = styled(Box)(({ theme }) => ({
  padding: "4px",
  marginX: "10px",
  minHeight: "25vh",
  borderRight: `2px solid ${theme.palette.primary.main}`,
  justifyContent: "center",
}));

const ContentBox = styled(Box)({
  display: "flex",
  alignItems: "start",
  justifyContent: "center",
  flexDirection: "column",
  marginBottom: "4px",
});

const AnswersBox = styled(Box)({
  height: "160px",
  overflowY: "auto",
});

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/CreateRegularQuestion.tsx
> +              // disabled={!isValid}
comment

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/QuestionSummary.tsx
> +          <Alert
What is the purpose of this alert? Web backoffice is exclusive only for internal team

2024-08-30 15:39 UTC, JMSevilla commented on packages/core-library/tests/page/QuestionSummary.test.tsx
> +import { fireEvent, render, screen } from "core-library/tests/common";
use the actual path

2024-08-30 15:47 UTC, acostales08 commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/CreateRegularQuestion.tsx
> +              // disabled={!isValid}
this file is not included i have changes here just to test the step 3

2024-08-31 12:09 UTC, acostales08 commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/QuestionSummary.tsx
> +          <Alert
![image](https://github.com/user-attachments/assets/87774bbb-43e9-4ce7-a4e0-ec959100f85d)

2024-09-01 07:39 UTC, JezChristian commented on packages/core-library/components/blocks/AnswerOptions/blocks/SATA/SATA.tsx
> +} from "../../../..";
Is there a way for the import not to be "../../../.." ?

2024-09-01 07:39 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/SuccessPage.tsx
> +    // <div
Comments Found

2024-09-01 08:05 UTC, DropitupQwerty commented on packages/core-library/components/blocks/AnswerOptions/blocks/SATA/SATA.tsx
> +} from "../../../..";
this is allowed as of now base on my last merge. It causes build failure when importing component from the "core-library/component/**" when you are in core library

2024-09-01 17:36 UTC, JezChristian approved these changes

2024-09-02 04:29 UTC, JMSevilla approved these changes

2024-09-02 12:06 UTC, DropitupQwerty approved these changes

2024-09-02 12:08 UTC, EderDM approved these changes

2024-09-02 12:22 UTC, merged