@86eq2zzue #Added Forgot and Change Password UI with Mock Questions
JMSevilla/nclexpower_turbo pull request #253
Opened 2024-08-30 03:31 UTC by BryanPalad

2024-08-30 08:24 UTC, JezChristian requested changes

2024-08-30 11:09 UTC, JMSevilla requested changes

2024-08-30 11:09 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/blocks/page/ChangePassword/ChangePasswordForm.tsx
> +import { Box, IconButton } from "@mui/material";
My overall comment on your code was.

1. It should have a `separation of concerns` wherein we can create a separate component for each block you added here.
2. Stay DRY 
3. Create a hook to utilize the functionality of this form. 

Here's what you need to do: 
1. Adjust your schema as this 
export const combinedPasswordSchema = yup.object({
  securityQuestion: yup.string().required("Select security question").default(""),
  securityAnswer: yup.string().required("Provide your answer").default(""),
  newPassword: yup.string().required("Provide your new password").default(""),
  confirmPassword: yup
    .string()
    .oneOf([yup.ref("newPassword")], "Password does not match")
    .required("Confirm your password")
    .default(""),
});

export type CombinedPasswordType = yup.InferType<typeof combinedPasswordSchema>;

export const CombinedPasswordAtom = atom<CombinedPasswordType | undefined>(
  undefined
);

2. Create a hook to utilize the functionality, on this hook you can add your schema integration. Create a hook named `usePasswordChange()`

import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import { combinedPasswordSchema, CombinedPasswordType } from "./schemas";

export default function usePasswordChange() {
  const { handleSubmit, control, watch } = useForm<CombinedPasswordType>({
    resolver: yupResolver(combinedPasswordSchema),
    defaultValues: combinedPasswordSchema.getDefault(),
  });

  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [showAlert, setShowAlert] = useState(false);
  const [validSecQAndSecA, setValidSecQAndSecA] = useState(false);

  const handleClickShowPassword = () => setShowPassword((prev) => !prev);
  const handleClickShowConfirmPassword = () => setShowConfirmPassword((prev) => !prev);

  const handleSubmitForm = (data: CombinedPasswordType) => {
    // Handle combined form submission
    if (!validSecQAndSecA) {
      // Handle security question validation
      setShowAlert(true);
      setValidSecQAndSecA(true);
    } else {
      // Handle password change logic
    }
  };

  const isSecQandAValid = !!watch("securityQuestion") && !!watch("securityAnswer");

  return {
    handleSubmit,
    control,
    showAlert,
    validSecQAndSecA,
    handleSubmitForm,
    isSecQandAValid,
    showPassword,
    showConfirmPassword,
    handleClickShowPassword,
    handleClickShowConfirmPassword,
  };
}

**Separation of concerns**
1. Create a separate functions inside your form file `Header` -> with this you can add your conditional rendering `showAlert`, 
2. next create a separate function `SubmitButton` which passes the parameters `{ isSecQandAValid, validSecQAndSecA, handleSubmitQandA, handleSubmitPassword }` , 
3. next Create a separate function which is `ChangeEmailLink`
4. next Create a separate function for `AnimationSection` wherein you implemente the lottie
5. next Create a separate function for `SecurityQuestionForm` 
6. next Create a separete function for `PasswordChangeForm` 
7. Lastly create the parent function `PasswordChangeSection` on this function you can use the hook `usePasswordChange` and integrate all the functions I mentioned above 

Now you can implement/do this all inside your one file without creating another

2024-08-30 11:09 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/account/forgot-password.tsx
> +function ForgotPasswordPage() {
You should use our existing implementation which is the newest one using `ParseBlocks` you can find this file on our `core-library/system/app/internal/parse-blocks.tsx`

2024-08-31 09:57 UTC, BryanPalad commented on apps/web-backoffice-generic/src/components/blocks/page/ChangePassword/ChangePasswordForm.tsx
> +import { Box, IconButton } from "@mui/material";
Comments Addressed

2024-08-31 10:00 UTC, BryanPalad commented on apps/web-backoffice-generic/src/pages/account/forgot-password.tsx
> +function ForgotPasswordPage() {
I've tried using ParseBlocks and transfer my blocks folder to the core-library, but the design didn't work properly because Tailwind is not yet implemented in the core-library

2024-08-31 13:52 UTC, JezChristian requested changes

2024-08-31 13:52 UTC, JezChristian commented on apps/web-backoffice-generic/src/components/blocks/page/EmailVerification/EmailVerificationForm.tsx
> +
Remove Spacing

2024-08-31 13:52 UTC, JezChristian commented on apps/web-backoffice-generic/src/components/blocks/page/EmailVerification/EmailVerificationForm.tsx
> +            <Link
you can use useRouter to redirect to login

const router = useRouter()
router.push({pathname: '/login'})

2024-08-31 13:52 UTC, JezChristian commented on apps/web-backoffice-generic/src/components/blocks/page/PasswordChange/components/BackToChangeEmail.tsx
> +      href={href}
you can use useRouter to redirect to login

2024-08-31 13:55 UTC, JMSevilla approved these changes

2024-08-31 13:55 UTC, JezChristian requested changes

2024-08-31 13:55 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/LoginFormBlock/LoginForm.tsx
> +            href="/account/forgot-password"
you can use useRouter to redirect to login

2024-08-31 14:04 UTC, JezChristian approved these changes

2024-08-31 14:19 UTC, DropitupQwerty approved these changes

2024-08-31 14:41 UTC, be3jaay approved these changes

2024-08-31 19:05 UTC, LizterBabael approved these changes

2024-09-01 11:08 UTC, JMSevilla approved these changes

2024-09-02 04:30 UTC, merged