@86eq11bp3 #Page Loader Web Customer
JMSevilla/nclexpower_turbo pull request #255
Opened 2024-08-30 15:05 UTC by JezChristian

2024-08-30 16:05 UTC, JMSevilla requested changes

2024-08-30 16:05 UTC, JMSevilla commented on packages/core-library/tests/hooks/usePageLoader.test.ts
> +
Spacing

2024-08-30 16:05 UTC, JMSevilla commented on packages/core-library/tests/hooks/usePageLoader.test.ts
> +
Spacing

2024-08-30 16:07 UTC, acostales08 approved these changes

2024-08-30 18:50 UTC, DropitupQwerty approved these changes

2024-08-30 20:36 UTC, JMSevilla requested changes

2024-08-30 20:36 UTC, JMSevilla commented on packages/core-library/tests/components/SidebarListButton.test.tsx
> +import { render } from '@testing-library/react';
We should use render from our common.

2024-08-31 03:10 UTC, JMSevilla approved these changes

2024-08-31 03:30 UTC, merged