@86epv04hg #Revoke Token Once logout Integration
JMSevilla/nclexpower_turbo pull request #259
Opened 2024-09-01 18:47 UTC by LizterBabael

* Integrate Revoke token on logout

2024-09-02 12:32 UTC, DropitupQwerty approved these changes

2024-09-03 11:03 UTC, be3jaay approved these changes

2024-09-03 11:03 UTC, be3jaay commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    // Assertions
remove comment

2024-09-03 13:01 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    expect(mockRevokeCb).toHaveBeenCalled();
Your test statement says `if revoke callback is not called` but here you are expecting `mockRevokeCb` is called ?

2024-09-03 13:01 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    expect(mockRevokeCb).toHaveBeenCalledWith({
Same as this

2024-09-03 13:03 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthHooks.test.tsx
> +import { renderHook } from "../common";
What is `AuthHooks` ? is this file existing on our codebase ? I guess not. please create filename accordingly

2024-09-03 15:12 UTC, EderDM approved these changes

2024-09-04 04:24 UTC, DropitupQwerty approved these changes

2024-09-04 12:16 UTC, acostales08 approved these changes

2024-09-05 05:58 UTC, JMSevilla requested changes

2024-09-05 05:58 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    const mockClearCookies =
This is not the proper way to clear our session storage

I guess instead of clearing them all one by one, you can use this function to mock

![image](https://github.com/user-attachments/assets/36e02da6-bea5-4be3-8d37-6091383dffad)

2024-09-05 05:58 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    (useSensitiveInformation as jest.Mock).mockReturnValue({
You already mocking this information above is there any problem when this is removed?

2024-09-05 05:58 UTC, JMSevilla commented on packages/core-library/tests/contexts/AuthContext.test.tsx
> +    expect(mockClearCookies).toHaveBeenCalled();
So instead of using this we can use 

![image](https://github.com/user-attachments/assets/8d5d6911-bc99-477b-9537-ebfec76dc043)

2024-09-05 16:02 UTC, JMSevilla approved these changes

2024-09-05 16:03 UTC, merged