Enhancement/86eq5k2ud add tooltip on simulator header
JMSevilla/nclexpower_turbo pull request #296
Opened 2024-09-11 15:49 UTC by nasolgabriel

added tooltip to simulator header options

![image](https://github.com/user-attachments/assets/ac37f507-4d97-470d-b434-e2830d826e3a)
![image](https://github.com/user-attachments/assets/2af25d29-e1b9-43ee-9273-b93f7ac24704)

2024-09-11 16:57 UTC, DropitupQwerty commented on apps/simulator/src/components/Toolbar/Toolbar.tsx
> +  const toolTipData = [
Can you seperate this in our constant?

2024-09-11 17:06 UTC, DropitupQwerty requested changes

2024-09-11 17:06 UTC, DropitupQwerty commented on apps/simulator/src/components/Header/Header.tsx
>                        />{' '}
Do you use this blank space as space?

2024-09-11 17:06 UTC, DropitupQwerty commented on apps/simulator/src/components/Toolbar/Toolbar.tsx
> +  const toolTipData = [
Can you isolate this in a constant folder?

2024-09-12 00:41 UTC, JMSevilla requested changes
Please address existing comments

2024-09-12 06:52 UTC, be3jaay requested changes

2024-09-12 06:52 UTC, be3jaay commented on apps/simulator/src/components/Toolbar/Toolbar.tsx
> +            ))}
You didn't used the index, I believed there will be a warning on console when you didn't put a unique "key" prop in a list, 
```suggestion
            {toolTipData.map((item,index)=>(
              <CustomTooltip key={index} title={item.title}>
                <Button sx={iconStyle}>
                  {item.icon} 
                </Button>
            </CustomTooltip>
            ))}
```

2024-09-16 02:34 UTC, be3jaay requested changes

2024-09-16 02:34 UTC, be3jaay commented on apps/simulator/src/core/constant/toolTipDataConstant.tsx
> +export const ToolTipData = () => {
Your file name should match the name of the component. Also, toolTipDataConstant is too long (TooltipData is enough).

2024-09-16 08:04 UTC, nasolgabriel commented on apps/simulator/src/core/constant/toolTipDataConstant.tsx
> +export const ToolTipData = () => {
toolTipDataConstant already renamed

2024-09-16 09:14 UTC, be3jaay approved these changes

2024-09-17 07:54 UTC, JMSevilla approved these changes

2024-09-17 12:32 UTC, LizterBabael approved these changes

2024-09-17 13:24 UTC, DropitupQwerty approved these changes

2024-09-17 13:39 UTC, merged