@86eq86jkx #Router implementation under Regular Question Bad practice…
JMSevilla/nclexpower_turbo pull request #298
Opened 2024-09-11 18:34 UTC by acostales08

-reset if route change
-some changes in loader and animationLoader to avoid hydration

2024-09-12 00:36 UTC, JMSevilla requested changes

2024-09-12 00:36 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/loader.tsx
> +const isTrue = true.toString();
What is this ?

2024-09-12 00:36 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/SettingsManagementPageForm.tsx
> +  useEffect(() => {
I'm not sure if this implementation is even maintainable. Can we use useBeforeUnload ?

2024-09-14 01:52 UTC, BryanPalad approved these changes

2024-09-14 19:19 UTC, EderDM approved these changes

2024-09-17 07:51 UTC, JMSevilla requested changes

2024-09-17 07:51 UTC, JMSevilla commented on packages/core-library/core/hooks/useResetOnRouteChange.ts
> +export const useResetOnRouteChange = ({resetStep}: Props) => {
With this implementation application won't ask if he/she currently had some changes right? which leads of data loss when user is unintentionally navigates to other pages.

2024-09-19 13:44 UTC, JMSevilla approved these changes

2024-09-19 16:04 UTC, merged