Feature/86epu9yre/wc watch tutorial UI
JMSevilla/nclexpower_turbo pull request #329
Opened 2024-09-30 04:16 UTC by BryanPalad

![WatchTutorialDesktopTheater](https://github.com/user-attachments/assets/7a3f77e4-6500-432e-8959-f919455c3cc1)
![WatchTutorialDesktop](https://github.com/user-attachments/assets/cbc44630-7af6-4ed5-9029-e85cd56787a3)
![WatchTutorialMobile](https://github.com/user-attachments/assets/6f5abcfb-3ddc-445d-894c-67b757b41f17)
![WatchTutorialTablet](https://github.com/user-attachments/assets/2ebe9fa5-f16a-415d-9a9b-b863c22f2713)
![WatchTutorialMobile2](https://github.com/user-attachments/assets/dc084e19-4bae-489c-85b5-94d978841adb)

2024-09-30 05:15 UTC, JMSevilla requested changes

2024-09-30 05:15 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/WatchVideosBlock/VideoPlayer.tsx
> +  const playerWidth = isWideScreen
This implementation is too generic

2024-09-30 05:15 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/WatchVideosBlock/VideoPlayer.tsx
> +  const playerHeight = isWideScreen
This implementation is too generic

2024-09-30 05:15 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/WatchVideosBlock/VideoWatchList.tsx
> +        {sectionVideos?.map((item) => {
same comment above

2024-09-30 05:15 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/WatchVideosBlock/VideoWatchList.tsx
> +          const isSelected = selectedVid?.secVidId === secVidId;
Btw we weren't using number for id if somehow this is connected on the backend , we are always using GUID

2024-09-30 05:15 UTC, JMSevilla commented on apps/web-customer/src/pages/hub/programs/watch/index.tsx
> +export default withAuth(WatchVideoPage);
I'm not sure if you should use this now since we are still investigating this hook if it is fully adaptive for both platforms.

2024-09-30 10:11 UTC, BryanPalad commented on apps/web-customer/src/components/AccordionList/AccordionDetails.tsx
> +    router.push(`/hub/programs/watch?secVids=${encodedSecVids}&programId=${programId}`);
Added https://app.clickup.com/t/86eqd1m3h

2024-10-01 09:23 UTC, JMSevilla approved these changes

2024-10-01 13:58 UTC, be3jaay approved these changes

2024-10-02 13:20 UTC, DropitupQwerty approved these changes

2024-10-02 13:38 UTC, merged