@86eqdp41g #CAA Reviewer Page DateField Implementation
JMSevilla/nclexpower_turbo pull request #346
Opened 2024-10-08 09:20 UTC by be3jaay

2024-10-08 15:01 UTC, JMSevilla requested changes

2024-10-08 15:01 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +export default function ContentReviewerForm({ }: Props) {
we shouldn't add anything from the function like this `Props` if it is not yet used.

2024-10-08 16:52 UTC, JMSevilla requested changes

2024-10-08 16:52 UTC, JMSevilla commented on apps/web-backoffice-generic/src/components/Blocks/Account/PasswordChange/PasswordChangeBlock.tsx
> +import { LottieAnimation } from "core-library/system/app/internal/blocks/Account/PasswordChange/components/LottieAnimation/LottieAnimation";
It is good that we have our unique implementation here but can we add this component to index.ts ? so when we need to use it will not get the full path ?

2024-10-09 02:36 UTC, JMSevilla approved these changes

2024-10-09 09:46 UTC, JezChristian approved these changes

2024-10-09 10:40 UTC, nasolgabriel approved these changes

2024-10-09 10:41 UTC, merged