@86epx9xt3 #step3 of BG info Items and TableView
JMSevilla/nclexpower_turbo pull request #349
Opened 2024-10-09 14:52 UTC by acostales08

2024-10-10 04:11 UTC, JMSevilla requested changes

2024-10-10 04:11 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/ItemContent.tsx
> +  const validQuestionnaires =
Can we instead use this kind of structure here

const VALID_QUESTION_TYPES = ["DDC", "SATA", "MRSN"];

const validQuestionnaires = values.questionnaires?.filter(
  (item): item is QuestionnaireItem => VALID_QUESTION_TYPES.includes(item.questionType)
) || [];

2024-10-10 04:11 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/items.tsx
> +export const Items: React.FC<{ content: QuestionnaireItem[] }> = ({
Kindly follow this code improvement 

use this constant to replace your sx that looks like repeating it self in other component 
const wordWrapStyles: SxProps<Theme> = {
    "& *": {
      margin: 0,
      padding: 0,
      lineHeight: 1.5,
      wordBreak: "break-word",
    },
  };
  
  
  don't forget to always follow `Separation of concerns`
  
  const renderQuestionType = (
  data: QuestionnaireItem,
  purifyInputs: (input: string) => string | TrustedHTML
) => {
  if (data.questionType === "DDC") {
    return (
      <DDCquestion
        ddcData={{
          answers: data.answers as DDCAnswerOption[],
          itemStem: data.itemStem,
        }}
      />
    );
  } else {
    return (
      <Typography
        sx={{
          "& *": {
            margin: 0,
            padding: 0,
            lineHeight: 1.5,
            wordBreak: "break-word",
          },
        }}
        dangerouslySetInnerHTML={{
          __html: purifyInputs(data.itemStem) as TrustedHTML,
        }}
      />
    );
  }
};

// Helper function to render labels for SATA and MRSN question types
const renderQuestionTypeLabel = (data: QuestionnaireItem) => {
  if (data.questionType === "SATA") {
    return (
      <Typography marginTop="14px" fontSize="16px" color="#999999" fontWeight="700">
        Select All That Apply
      </Typography>
    );
  } else if (data.questionType === "MRSN") {
    return (
      <Typography marginTop="14px" fontSize="16px" color="#999999" fontWeight="700">
        {`Select ${data.maxAnswer} That Apply`}
      </Typography>
    );
  }
  return null; // No label for other types
};

// Helper component to render answers
const AnswerList: React.FC<{ answers: Answer[] }> = ({ answers }) => {
  return (
    <Box marginTop="10px">
      {answers.map((answer) => (
        <Box display="flex" alignItems="center" paddingX="10px" key={answer.id}>
          <Checkbox disabled checked={answer.answerKey} />
          <Typography fontSize="16px">{answer.answer}</Typography>
        </Box>
      ))}
    </Box>
  );
};

2024-10-10 04:11 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/TableView.tsx
> +export const TableView: React.FC<Props> = ({ data }) => {
Can we instead use our `DataTable` component here again you created another component which we already have.

2024-10-12 13:04 UTC, JMSevilla requested changes

2024-10-12 13:04 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudySummary/component/Items/items.tsx
> +export const wordWrapStyles: SxProps = {
If I'm not mistaken we do have a hook to place the styling for each component, coordinate with sam or jb

2024-10-13 16:52 UTC, JMSevilla approved these changes

2024-10-14 13:20 UTC, DropitupQwerty approved these changes

2024-10-14 14:04 UTC, merged