@86eqdy1f8 #Revamped UI for Internal User Form
JMSevilla/nclexpower_turbo pull request #353
Opened 2024-10-10 13:24 UTC by be3jaay

2024-10-10 15:28 UTC, LizterBabael requested changes

2024-10-10 15:28 UTC, LizterBabael commented on packages/core-library/system/app/internal/blocks/Hub/ManageUser/internal-users/InternalUsersForm.tsx
> +    console.log(selectedObjects);
remove console.log

2024-10-11 02:41 UTC, JMSevilla approved these changes

2024-10-11 04:07 UTC, LizterBabael approved these changes

2024-10-11 10:58 UTC, DropitupQwerty approved these changes

2024-10-11 11:08 UTC, merged