@86eq301uc #WB Content Loader on Submit
JMSevilla/nclexpower_turbo pull request #359
Opened 2024-10-12 13:22 UTC by BryanPalad

2024-10-13 16:48 UTC, JMSevilla requested changes

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/components/ComponentLoader.tsx
> +  position?: Property.Position;
Is this necessary or can we use the props from MUI ?

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/components/ComponentLoader.tsx
> +      position={position}
Since we are just using the position `relative` I guess this is doable by default from MUI right ?

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +  const [isLoading , setIsLoading] = useState<boolean>(false);
Kindly use this > usePageLoaderContext

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +  const onSubmit = async (values: crbType) => {
A much better format her will be `async function onSubmit() {}`

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +    reset();
You can implement this reset() to finally

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +        setIsApproved(true);
Is it the `setIsApproved` state should be set dynamically instead setting it generically like this?

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +        {isLoading && (
we can set the component loader outside of `return ()` like 

if(isLoading) return <ComponentLoader />

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +            {author.map((item, index) => (
We should have a catch here whenever we presented an empty array.

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +        {showModal ? (
This can also be outside of return ()

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +                  <TextField
We can use our newly build TextAreaField

2024-10-13 16:48 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +                    isLoading={false}
we should pass loading value here.

2024-10-14 11:08 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +  const onSubmit = async (values: crbType) => {
Noted

2024-10-14 11:09 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +    reset();
Noted

2024-10-14 11:10 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +        {isLoading && (
Noted

2024-10-14 11:20 UTC, BryanPalad commented on packages/core-library/components/ComponentLoader.tsx
> +      position={position}
position={position} is removed

2024-10-14 11:26 UTC, BryanPalad commented on packages/core-library/components/ComponentLoader.tsx
> +  position?: Property.Position;
3 props removed

2024-10-14 12:04 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +                  <TextField
Noted

2024-10-14 12:08 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +                    isLoading={false}
changed to isLoading={isLoading ?? false}, if isLoading is undefined it will fallback to false

2024-10-14 12:25 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +            {author.map((item, index) => (
Will display text "Author details unavailable" if author array is empty.

2024-10-14 12:34 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +  const [isLoading , setIsLoading] = useState<boolean>(false);
Noted.

2024-10-14 12:41 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerBlock.tsx
> +        setIsApproved(true);
setIsApproved will be used when an api is available, setIsApproved to true once the data is submitted succcesfully. otherwise throw an error or prompt.

2024-10-14 12:42 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +                    isLoading={false}
Added isLoading={contentLoader ?? false}, this will ensure that if contentLoader is undefined, it will fallback to false

2024-10-14 12:52 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +        {showModal ? (
Noted.

2024-10-14 17:58 UTC, JMSevilla requested changes

2024-10-14 17:58 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +  const modalContent = showModal ? (
I mean for this one, no need to create a constant here since based on your current solution here you just compress them to a constant but still it is not separated. 

if (showModal) { 
 return ...your jsx
}

2024-10-14 17:58 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +    <Box
While this code has been under on `else` this can be rendered directly on your return below.

2024-10-15 04:57 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +  const modalContent = showModal ? (
![image](https://github.com/user-attachments/assets/6c6acc01-32b3-41e9-a14f-93eb71f1161e)
This will be the output if I put the showModal condition outside the return. Content Details doesn't display,

this showModal conditionally render the button review changes button and pick a date modal

2024-10-15 10:48 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +    <Box
{showModal ?} have been reverted below the return.

2024-10-15 11:28 UTC, JMSevilla approved these changes

2024-10-15 11:59 UTC, be3jaay approved these changes

2024-10-15 13:17 UTC, DropitupQwerty approved these changes

2024-10-15 13:20 UTC, merged