86eq8pbvd #In App Form Restructure
JMSevilla/nclexpower_turbo pull request #361
Opened 2024-10-14 04:40 UTC by JezChristian

Bulk Creation of Menu
![brave_1yFVwlwZRr](https://github.com/user-attachments/assets/c1d9f76a-cce5-476c-9abe-22e125649fcc)

Sample Payload
![brave_Kahq4L5q2l](https://github.com/user-attachments/assets/459240cd-64c6-41fa-9c95-2c8307704187)

2024-10-14 10:12 UTC, JMSevilla requested changes

2024-10-14 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/components/RouteCreationForm.tsx
>      console.log("values : ", values);
I saw the payload it almost get all the data but there's a missing one which is the `icon` i believe

here's the example payload data we have when creating a menu 

{
    "label": "Dashboard",
    "icon": "DashboardIcon",
    "path": "",
    "children": [
      {
        "label": "Performance",
        "icon": "DashboardIcon",
        "path": "/"
      }
    ]
  },

2024-10-14 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/components/RouteCreationForm.tsx
> +        {SysReq.length > 0 &&
Please use an appropriate naming

2024-10-14 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/components/RouteCreationForm.tsx
> +        {fields.length > 0 &&
This can be implement to a separate function, always remember `Separation of concerns`

2024-10-14 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/components/RouteCreationForm.tsx
> +                {menuItem.type === "Main" ? (
The conditioning here can be improved in a separate function like using `switch casing`

2024-10-14 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/constant/constant.tsx
> +    value: "0",
Are we converting this value to number ? or are we planning to send this to our api as string ?

2024-10-14 18:27 UTC, JMSevilla requested changes

2024-10-14 18:27 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/components/MenuSelector.tsx
> +    case "Main":
Create separate function to render this 2 conditional components.. as I explained just now.

2024-10-15 11:27 UTC, JMSevilla approved these changes

2024-10-15 12:47 UTC, LizterBabael approved these changes

2024-10-15 13:19 UTC, BryanPalad approved these changes

2024-10-15 13:38 UTC, merged