@86eqemm1q#WC- Contact us Change Text Field to Phone Field
JMSevilla/nclexpower_turbo pull request #362
Opened 2024-10-14 07:31 UTC by emmanlemon

2024-10-14 10:18 UTC, JMSevilla requested changes

2024-10-14 10:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/validation.ts
> +  countryCode: yup
Adding this schema will look like it should be required by the user or it should automatically be occupied by our application. you can instead do this

phoneCode: yup.string().default(DEFAULT_PHONE_COUNTRY_CODE)

this `DEFAULT_PHONE_COUNTRY_CODE` can be found in `constant.ts`

2024-10-14 10:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
> +      countryCode={countryCode}
how about `form.watch('phoneCode')` much simpler and no need to initialize useWatch ?

2024-10-15 03:30 UTC, emmanlemon commented on apps/web-customer/src/components/blocks/ContactBlock/validation.ts
> +  countryCode: yup
The validation.ts file already has DEFAULT_PHONE_COUNTRY_CODE for country code.

2024-10-15 03:32 UTC, emmanlemon commented on apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
> +      countryCode={countryCode}
I have already included a watch in the country code field.

2024-10-15 10:52 UTC, acostales08 approved these changes

2024-10-15 11:25 UTC, JMSevilla approved these changes

2024-10-15 11:29 UTC, BryanPalad approved these changes

2024-10-16 00:28 UTC, emmanlemon commented on apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
>  import React from "react";
Added Comment on every file.

2024-10-16 01:31 UTC, JMSevilla approved these changes

2024-10-16 14:18 UTC, merged