@86eqfu18z #Button UI adjustments on web customer
JMSevilla/nclexpower_turbo pull request #368
Opened 2024-10-16 16:50 UTC by DropitupQwerty

2024-10-16 18:09 UTC, JMSevilla requested changes

2024-10-16 18:09 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
> +              <TextField
We should start using our component `TextAreaField` component

2024-10-17 03:07 UTC, JMSevilla approved these changes

2024-10-17 03:22 UTC, BryanPalad approved these changes

2024-10-17 10:23 UTC, JezChristian approved these changes

2024-10-17 10:23 UTC, merged