@feature/86ep32763/skeleton-loading
JMSevilla/nclexpower_turbo pull request #39
Opened 2024-05-11 11:36 UTC by JezChristian

2024-05-15 09:12 UTC, JMSevilla requested changes

2024-05-15 09:12 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +    return questionKey == "RegularQuestions" ?
This is not the right way

2024-05-15 09:49 UTC, JezChristian commented on apps/simulator/src/components/parse-contents.tsx
> +    return questionKey == "RegularQuestions" ?
Any suggestion sir?

2024-05-16 09:30 UTC, JMSevilla requested changes

2024-05-16 09:30 UTC, JMSevilla commented on apps/simulator/src/components/SkeletonLoader/AnimatedBoxSkeleton.tsx
> +export const AnimatedBoxSkeleton: React.FC<QuestionType> = ({ height }) => {
You are just passing 1 props why don't you just add the height directly to this component. Then instead of using React.FC just use = () => {}

2024-05-17 08:09 UTC, JMSevilla requested changes

2024-05-17 08:09 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +const RegularQuestionSkeleton = () => {
Same comment from above.

2024-05-17 08:09 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +    if (isLoading) {
This is not the proper implementation

2024-05-17 08:09 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +    if (isLoading) {
same comment above

2024-05-17 08:09 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +          console.log(QuestionType);
remove console

2024-05-20 07:20 UTC, JMSevilla requested changes

2024-05-20 07:20 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +      :
Code under this else block is too messy. Can you clean this up

2024-05-20 10:35 UTC, DropitupQwerty approved these changes

2024-05-20 13:59 UTC, acostales08 approved these changes

2024-05-20 14:00 UTC, merged