@86eqhnmjc #Customer Account Creation
JMSevilla/nclexpower_turbo pull request #392
Opened 2024-10-19 17:29 UTC by BryanPalad

![image](https://github.com/user-attachments/assets/f04eb3c4-3aab-43a9-99f0-f06509f66d83)

2024-10-21 16:17 UTC, JezChristian requested changes

2024-10-21 16:17 UTC, JezChristian commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +import ArrowBackIosNewIcon from "@mui/icons-material/ArrowBackIosNew";
Maybe we can now transition to Eva Icons?

2024-10-21 16:40 UTC, DropitupQwerty requested changes

2024-10-21 16:40 UTC, DropitupQwerty commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +    orderNumber: string | undefined;
remove undefined so we can assure that this field will be filled by orderNumber

2024-10-21 16:40 UTC, DropitupQwerty commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +interface AccountCreationData {
isolate this type in our types.ts

2024-10-21 16:44 UTC, DropitupQwerty requested changes

2024-10-21 16:44 UTC, DropitupQwerty commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +                  disabled={submitLoading}
Disable this button if 2 checkbox is not checked

2024-10-22 05:31 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +    orderNumber: string | undefined;
![image](https://github.com/user-attachments/assets/9bb9065d-a757-4b3c-8b44-874232a9d36d)
this was the hook for fetching orderNumber, fyi

2024-10-22 06:00 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +                  disabled={submitLoading}
I also implemented the button disabled if the form is not complete.

2024-10-22 07:33 UTC, JMSevilla requested changes

2024-10-22 07:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +  const firstname = watch("firstname");
Instead of watching them all, why not use isDirty from useForm ?

2024-10-22 07:33 UTC, JMSevilla commented on packages/core-library/components/EvaIcon.tsx
> +  onClick?: () => void;
Instead of passing onClick from the EvaIcon why not if you use it contain it with IconButton ?

2024-10-22 07:33 UTC, JMSevilla commented on packages/core-library/components/EvaIcon.tsx
> +    <Box onClick={onClick}>
We shouldn't adding onClick on this component since the purpose of it is to just present an icon.

2024-10-22 07:33 UTC, JMSevilla commented on packages/core-library/types/types.ts
> +  middlename: string;
since middlename can be empty it should be string | undefined or null ?

2024-10-22 07:33 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +            orderNumber: orderNumber || "",
orderNumber can't be empty

2024-10-22 07:35 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +    orderNumber: string | undefined;
undefined is fine here as long as you validate the orderNumber before putting the value to the potential payload

2024-10-22 10:29 UTC, BryanPalad commented on packages/core-library/types/types.ts
> +  middlename: string;
Noted..

2024-10-22 10:29 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +  const firstname = watch("firstname");
Noted..

2024-10-22 10:39 UTC, BryanPalad commented on packages/core-library/components/EvaIcon.tsx
> +    <Box onClick={onClick}>
onClick props has been removed from EvaIcon

2024-10-22 10:52 UTC, BryanPalad commented on packages/core-library/components/EvaIcon.tsx
> +  onClick?: () => void;
Do we have an IconButton component? or should I use 
<Button>
<Icon/>
</Button>

2024-10-23 03:52 UTC, be3jaay approved these changes

2024-10-23 08:02 UTC, JMSevilla requested changes

2024-10-23 08:02 UTC, JMSevilla commented on packages/core-library/components/Button/EvaIconButton.tsx
> +        <EvaIcon
We shouldn't add generic code here the goal is to make it dynamic

2024-10-23 09:03 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/OrderSummaryBlock/OrderSummaryBlock.tsx
> +    await router.push({ pathname: "/account/registration" });
Okay noted..

2024-10-25 06:03 UTC, JezChristian requested changes

2024-10-25 06:03 UTC, JezChristian commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +        //add createAccount api integration pass filteredValues as payload
Removed comment

2024-10-25 06:03 UTC, JezChristian commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +import { Visibility, VisibilityOff } from "@mui/icons-material";
Let's use Eva Icons.

2024-10-25 07:31 UTC, JMSevilla requested changes

2024-10-25 07:31 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +    const showToast = (message: string, type: "error" | "success") => {
This looks like a utilization we can use across our application. This implementation can be placed inside `useExecuteToast()`

2024-10-25 07:31 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +      if (!orderNumber) {
We shouldn't place any messages here since customer doesn't know about this and it will give them confusion.

In order to do this in a right way can you follow this: 
1. use inline validation for this 3 validations you have and just return nothing e.g, if (your.validations..) return;
2. Use try-catch as part of best practices. if you contain try-catch here whenever there's a problem in API call there should be a catch saying `something wen't wrong. please try again`

2024-10-25 07:31 UTC, JMSevilla commented on apps/web-customer/src/pages/account/registration/index.tsx
> + const RegistrationPage:React.FC = ()=> {
since we don't have any additional logics here you can use one-line implementation here

const jsn = () => ( ...your-block)

2024-10-26 04:08 UTC, LizterBabael approved these changes

2024-10-26 15:55 UTC, JMSevilla approved these changes

2024-10-26 16:28 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationBlock.tsx
> +        //add createAccount api integration pass filteredValues as payload
Noted

2024-10-26 17:01 UTC, DropitupQwerty approved these changes

2024-10-26 17:27 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/RegistrationBlock/RegistrationForm.tsx
> +import { Visibility, VisibilityOff } from "@mui/icons-material";
Noted

2024-10-27 07:35 UTC, JezChristian approved these changes

2024-10-27 07:57 UTC, merged