@86eq8pbvd #In-App-Delete-API-Integration-Version-2 Repush Due to aff…
JMSevilla/nclexpower_turbo pull request #397
Opened 2024-10-22 13:44 UTC by JezChristian

Changes :
Delete [API] Integration
Eva Icons Implementation
Temporary Delete Confirmation Modal Applied

2024-10-23 03:22 UTC, be3jaay requested changes

2024-10-23 03:22 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/InAppRouterManagement.tsx
> +// import { GridMoreVertIcon } from "@mui/x-data-grid";
Remove comment

2024-10-23 03:22 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/InAppRouterManagement.tsx
> +          <button
Question: Is there any reason, why did you not use the Button from the core-library?

2024-10-23 03:22 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/InAppRouterManagement.tsx
> +import { CustomPopover } from "../../../../../../../../../components/Popover/Popover";
I forgot to add this in index.ts from the core-library component, so maybe you can add this to the core-library components index. Thank you.

2024-10-23 04:06 UTC, JMSevilla requested changes

2024-10-23 04:06 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +import { CustomPopover } from "../../../../../../../../../../components/Popover/Popover";
Are we not able to import this `CustomPopover` above together with other components?

2024-10-23 04:06 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
> +import ConfirmationModal from "../../../../../../../../../../components/Dialog/DialogFormBlocks/RegularQuestion/ConfirmationDialog";
We should import this kind of component above together with other components.

2024-10-23 04:06 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/blocks/rqc/ContentReviewer/ContentReviewerForm.tsx
>  function MainContent() {
There are a few improvements that could enhance readability and performance:

1. Avoid using index as key: Instead of using the array index, it's better to use a unique property like item.id to prevent issues with React’s reconciliation when the list order changes.
2. Refactor inline styles: I recommend moving repetitive styles (like color: "#560bad") into a common styles object to avoid repetition and improve maintainability.
3. Semantic HTML: Since you’re rendering a list of answer options, consider using ul or ol for better semantic structure and accessibility.

2024-10-23 04:09 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/routing/InAppRouterManagement.tsx
> +          <button
This is not acceptable, every time you guys encountered something like this the last option you got is to import another component from the library instead of trying to modify our existing one.

2024-10-25 05:50 UTC, DropitupQwerty approved these changes

2024-10-25 07:23 UTC, JMSevilla approved these changes

2024-10-25 11:17 UTC, be3jaay approved these changes

2024-10-25 11:22 UTC, merged