@86eq39dnz #API Integraion and inclusion management ui
JMSevilla/nclexpower_turbo pull request #407
Opened 2024-10-26 10:12 UTC by DropitupQwerty

2024-10-28 08:47 UTC, JMSevilla requested changes

2024-10-28 08:47 UTC, JMSevilla commented on packages/core-library/api/web/web-api-backoffice.ts
> +    return await this.axios.post<number>(
We don't need to add number as response type here to identify if it is success or not. kindly based on response status.

2024-10-28 08:47 UTC, JMSevilla commented on packages/core-library/api/web/web-api-backoffice.ts
> +    return await this.axios.delete<number>(
We don't need to add number as response type here to identify if it is success or not. kindly based on response status.

2024-10-28 08:47 UTC, JMSevilla commented on packages/core-library/api/web/web-api-backoffice.ts
> +    return await this.axios.put<number>(
We don't need to add number as response type here to identify if it is success or not. kindly based on response status.

2024-10-28 08:47 UTC, JMSevilla commented on packages/core-library/components/Dialog/DialogFormBlocks/inclusion/InclusionEditForm.tsx
> +            executeToast('Inclusion Already Exist', 'top-right', true, { type: 'error' })
Since message under the `catch` are we sure that all errors will be coming from an existing inclusions? what if we encountered some errors such as 400, 500.

2024-10-28 08:52 UTC, be3jaay commented on packages/core-library/components/Dialog/DialogFormBlocks/inclusion/InclusionEditForm.tsx
> +import { Button } from '../../../Button/Button'
```suggestion
import { Button, TextField } from 'your-path-here'
```

2024-10-29 12:06 UTC, JMSevilla approved these changes

2024-10-29 12:31 UTC, JezChristian approved these changes

2024-10-29 12:44 UTC, be3jaay approved these changes

2024-10-29 13:54 UTC, merged