Feature/86eqftzu2-Login-Design-Adjustment
JMSevilla/nclexpower_turbo pull request #408
Opened 2024-10-27 09:15 UTC by nasolgabriel

minor adjustments in WC login

- fixed back button not visible in smaller screen by making the logo hidden
- adjusted the color of button border

2024-10-27 11:35 UTC, BryanPalad approved these changes

2024-10-27 11:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
> +              className="smaller-screen"
instead of adding inner style for checking mobile size, you can use our hook useResolution.

`const {isMobile} = useResolution();`

and add isMobile for conditional rendering of style on Image. Ex. style={{ display: isMobile ? 'none' : 'flex' }}

2024-10-27 11:36 UTC, BryanPalad requested changes

2024-10-27 11:36 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
>                style={{ width: "150px", height: "150px", objectFit: "cover" }}
instead of adding inner style for checking mobile size, you can use our hook useResolution.

`const {isMobile} = useResolution();`

and add isMobile for conditional rendering of style on Image. Ex. style={{ display: isMobile ? 'none' : 'flex' }}

2024-10-27 11:55 UTC, nasolgabriel commented on apps/web-customer/src/components/blocks/LoginFormBlock/LoginForm.tsx
>                style={{ width: "150px", height: "150px", objectFit: "cover" }}
currently doing it, thank you.

2024-10-27 14:09 UTC, be3jaay approved these changes

2024-10-27 14:57 UTC, BryanPalad approved these changes

2024-10-28 08:42 UTC, JMSevilla approved these changes

2024-10-28 08:43 UTC, merged