@86eqg3xvw #Added API integration for Submission of Subsequent options
JMSevilla/nclexpower_turbo pull request #409
Opened 2024-10-27 16:15 UTC by be3jaay

2024-10-28 08:41 UTC, JMSevilla requested changes

2024-10-28 08:41 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/ChatbotManagement/ChatbotDialogs.tsx
> +              loading={isSubmitting}
This comes from the schema we should also add the loading state during api call loading={isSubmitting || loading}

2024-10-29 02:48 UTC, BryanPalad approved these changes

2024-10-29 11:59 UTC, JMSevilla approved these changes

2024-10-29 12:41 UTC, nasolgabriel approved these changes

2024-10-29 12:42 UTC, merged