@enhancement/86ep326fg/highlight validation ft highlight component
JMSevilla/nclexpower_turbo pull request #43
Opened 2024-05-21 17:25 UTC by DropitupQwerty

- Creation of highlight component
- Highlight Validation
- Add hooks for extracting value inside brackets

2024-05-22 09:00 UTC, JMSevilla requested changes

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    const mergedText = Array.isArray(textToHighlight) ? textToHighlight.join(' \n \n ') : textToHighlight
This code can be isolate, transfer this in utils make this code reusable for others.

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    const groupedByConsecutiveIndex = (words: selectedWordType[]) => {
You can also transfer this in utils , so your code is more readable

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    const removeArrayDuplication = (words: selectedWordType[]) => {
Also for this code, transfer this in utils

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    useEffect(() => {
Your code inside useEffect can also be transfer.

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +        const handleHighlight = () => {
Add a try catch

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    useEffect(() => {
Can you just create a hook for all of your logic here ? then place your useEffects inside of it.

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    const convertNewline = wordsInItem.map((word) => word.replace(/\n/g, '<br/> '))
Did we test this when wordsInItem is undefined or empty? what if it is empty. what's our catch? 

You can also add wordsInItem.length > 0

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +        {convertNewline.map((word, index) => {
Did we test this when wordsInItem is undefined or empty? what if it is empty. what's our catch?

You can also add wordsInItem.length > 0

2024-05-22 09:00 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +            return word.includes('<br/>') ? <span dangerouslySetInnerHTML={theObj} /> : <span className={`${isHighlighted ? 'bg-yellow-300' : ''}`} aria-label={`${index}`} dangerouslySetInnerHTML={th
This can be done not directly in return () you can create a constant

const word = ... 

then return (
...
{word()} 
)

2024-05-22 16:24 UTC, JMSevilla requested changes

2024-05-22 16:24 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +        try {
You just added try catch you should transfer this whole code in your utils since the code is massive.

2024-05-22 16:24 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +            console.error(error)
Add additional message on your console error for us to track it much better.

2024-05-22 16:24 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    const renderText = (values: string[]) => {
We can also transfer this code in utils

2024-05-23 03:31 UTC, JMSevilla requested changes

2024-05-23 03:31 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +    return <div>
This doesn't need div you can return directly the function

2024-05-23 03:31 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCPComponent/HCPHighlighter.tsx
> +            console.log(values)
Remove console

2024-05-23 03:31 UTC, JMSevilla commented on apps/simulator/src/core/utils/useExtractBracket.tsx
> +export const useExtractBracket = (input: string) => {
Kindly check my previous comment about naming convention of this hook

2024-05-23 03:31 UTC, JMSevilla commented on apps/simulator/src/core/utils/useExtractBracket.tsx
> +                return `<b>${toReplace.content.replace(" ", '&nbsp')}</b>`
Is <b> means bold ? Can we replace it with strong ?

2024-05-24 07:11 UTC, JMSevilla approved these changes

2024-05-24 07:26 UTC, acostales08 approved these changes

2024-05-24 10:31 UTC, JezChristian approved these changes

2024-05-24 10:37 UTC, merged