@feature/86ep9fxm6/header loader for answer submission
JMSevilla/nclexpower_turbo pull request #48
Opened 2024-05-25 04:54 UTC by DropitupQwerty

- Install react top loading bar 
- Create header loader for asnwer submission

2024-05-28 02:37 UTC, JMSevilla requested changes

2024-05-28 02:37 UTC, JMSevilla commented on apps/simulator/src/components/Header/Header.tsx
> +  const [progress, setProgress] = useState<number>(10)
How can I able to reach this from the next button? this is only accessible in header. I suggest to create a Context API for this header progress bar.

2024-06-01 02:35 UTC, JMSevilla approved these changes

2024-06-01 02:35 UTC, JMSevilla commented on apps/simulator/src/core/context/ProgressContext.tsx
> +    const [progress, setProgress] = useState(10)
Kindly also extract setProgress for us to access this on our next button.

2024-06-01 10:06 UTC, acostales08 approved these changes

2024-06-01 13:02 UTC, merged