@feature/86epe34x6/Dropdown-table-Questionnaire-blocks
JMSevilla/nclexpower_turbo pull request #51
Opened 2024-05-25 08:51 UTC by acostales08

code refactoring

2024-05-26 07:51 UTC, JMSevilla requested changes

2024-05-26 07:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDTable/DDTable.tsx
> +                                    <TableContainer>
This code can be isolated from your questionnaire this looks like a component

2024-05-26 07:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDTable/DDTable.tsx
> +export const DDTable: React.FC<Props> = ({ questionaire, answer, selectedValues, handleSelectChange }) => {
Since table will be isolated change this name to different name

2024-05-26 07:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDTable/DDTable.tsx
> + interface SelectedValuesType {
We shouldn't store types/interface declaration here. you can transfer this to a global file we have from the core folder.

2024-05-31 14:17 UTC, JMSevilla approved these changes

2024-05-31 16:20 UTC, DropitupQwerty approved these changes

2024-05-31 18:38 UTC, JezChristian approved these changes

2024-05-31 18:39 UTC, merged