@feature/86epe3476/hcp questionnaire blocks
JMSevilla/nclexpower_turbo pull request #54
Opened 2024-05-26 15:33 UTC by DropitupQwerty

- HCP Questionnaire to HCP Blocks
- Update highlight background into inline CSS

2024-05-28 02:27 UTC, JMSevilla requested changes

2024-05-28 02:27 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCP/HCP.tsx
> +    const errorMessage = Array.isArray(formState.errors.hcp) ? formState.errors.hcp.map((err) => err?.message).pop() : formState.errors.hcp?.message
Try using hook useFocusOnError

2024-05-28 02:27 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCP/HCP.tsx
> +                                                                    ) : (
Kindly format your code with prettier.

2024-05-28 02:27 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/HCP/HCP.tsx
> +                                        {errorMessage && <FormHelperText error={true}>{errorMessage}</FormHelperText>}
This is not best practices, all the implementation for UI error handling is not consistent.

2024-05-31 01:27 UTC, JMSevilla requested changes

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/hcpUtils.tsx
>  export const renderHighlightText = (values: string[], highlightedWords: selectedWordType[]) => {
Ensure type annotations for function parameters and return types to improve type safety and readability.

export const renderHighlightText = (values: string[], highlightedWords: selectedWordType[]): JSX.Element[] => {

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/hcpUtils.tsx
> +  const highlightedWordIndices = highlightedWords.map((w) => w.wordIndex)
Use more descriptive variable names for better readability.

const highlightedIndices = highlightedWords.map((word) => word.wordIndex);

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/hcpUtils.tsx
> +    const convertNewLine = word.replace(/\n/g, '<br/> ')
Ensure the HTML conversion is safe and add comments to explain the logic

const htmlContent = word.replace(/\n/g, '<br/> ') + ' ';
const sanitizedContent = { __html: htmlContent };

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/hcpUtils.tsx
> +    const isHighlighted = highlightedWordIndices.includes(index)
Simplify and add comments to the logic checking if a word should be highlighted.

const isHighlighted = highlightedIndices.includes(index);

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/hcpUtils.tsx
> +      <span key={index} dangerouslySetInnerHTML={theObj} />
Use dangerouslySetInnerHTML carefully and ensure that the input is sanitized to avoid XSS vulnerabilities.

dangerouslySetInnerHTML={sanitizedContent}

Kindly use DOM purify npm install dompurify
DOMPurify.sanitize(htmlContent)

2024-05-31 01:27 UTC, JMSevilla commented on apps/simulator/src/core/utils/useValidationError.tsx
> +    if (errorMessages !== undefined) {
What if errorMessages is undefined? and can you add && errorMessages

2024-05-31 18:55 UTC, JMSevilla approved these changes

2024-05-31 18:56 UTC, acostales08 approved these changes

2024-05-31 18:56 UTC, JezChristian approved these changes

2024-05-31 18:58 UTC, merged