validation/86ep32677/MCQ-Validation - MCQ TABLE With MCQ Radio Button Component feat MCQ No Group Validation
JMSevilla/nclexpower_turbo pull request #56
Opened 2024-05-29 01:14 UTC by JezChristian

2024-05-29 07:30 UTC, JMSevilla requested changes

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +export const RadioButton: React.FC<Props> = ({
If this RadioButton isn't being used outside please remove export

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +                const handleChange = (onChange: any, selectedKey: string) => {
Ensure type safety for the handleChange function parameters. Replace any with more specific types.
const handleChange = (onChange: (value: boolean) => void, selectedKey: string)

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +            render={({ field: { value, onChange } }) => {
The destructuring of field inside the render prop is done correctly, but it could be made more readable by adding type annotations.

render={({ field: { value, onChange } }: { field: { value: boolean, onChange: (value: boolean) => void } }) => {

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +                const handleChange = (onChange: any, selectedKey: string) => {
Avoiding Inline Functions define handleChange outside of the render function to avoid recreating it on every render, improving performance.

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +                    onChange={() => handleChange(onChange, chKey)}
Ensure chKey is defined and handle potential issues where it might be undefined.

2024-05-29 07:30 UTC, JMSevilla commented on apps/simulator/src/components/MCQTableRadio.tsx
> +export const RadioButton: React.FC<Props> = ({
On your radiobutton use React.memo to wrap the RadioButton component to prevent unnecessary re-renders.

2024-05-31 19:26 UTC, JMSevilla approved these changes

2024-05-31 19:31 UTC, DropitupQwerty approved these changes

2024-05-31 19:36 UTC, acostales08 approved these changes

2024-05-31 19:36 UTC, merged