@enhancement/86epe33fv/CS-SATA-Questionnaire-blocks ft adding return …
JMSevilla/nclexpower_turbo pull request #63
Opened 2024-06-04 14:29 UTC by acostales08

…types

2024-06-04 15:34 UTC, DropitupQwerty approved these changes

2024-06-04 18:24 UTC, JMSevilla requested changes

2024-06-04 18:24 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/SATA/SATA.tsx
> +                                                <span><Checkbox value={answerItem.value} checked={checkedValues.includes(answerItem.value)} onChange={() => handleCheckBoxValues(answerItem.value)} sx=
setting a value can be improved don't add process inside the render when it is just setting a value.

2024-06-06 18:20 UTC, JMSevilla approved these changes

2024-06-06 23:54 UTC, JezChristian approved these changes

2024-06-07 09:51 UTC, merged