Enhancement/86epe342b/cs drop down cloze questionnaire blocks
JMSevilla/nclexpower_turbo pull request #64
Opened 2024-06-04 16:21 UTC by acostales08

2024-06-04 16:54 UTC, JMSevilla requested changes

2024-06-04 16:54 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDCloze/DDCloze.tsx
> +        const renderDropdown = (options: OptionType[], selectFieldKey: string) => {
Transfer this in a separate file in core > constant

2024-06-05 12:56 UTC, acostales08 commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDCloze/DDCloze.tsx
> +        const renderDropdown = (options: OptionType[], selectFieldKey: string) => {
dropdown reimplement ,renderDropdown function deleted

2024-06-05 16:51 UTC, DropitupQwerty commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDQuestionaire.tsx
Delete this file. This file is already exist in DND directory

2024-06-05 17:49 UTC, DropitupQwerty commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DDCloze/DDCloze.tsx
>                                          if (index % 2 === 0) {
Avoid using if condition inside mapping

2024-06-06 12:51 UTC, DropitupQwerty approved these changes

2024-06-06 18:19 UTC, JMSevilla approved these changes

2024-06-06 23:53 UTC, JezChristian approved these changes

2024-06-07 09:44 UTC, merged