@86epe34bg #code blocks refactoring in dnd questionnaire ft mcq block file renaming
JMSevilla/nclexpower_turbo pull request #65
Opened 2024-06-04 16:36 UTC by DropitupQwerty

- Renaming the MCQ Block file and updating of imports
- Dnd code block refactoring

2024-06-04 18:22 UTC, JMSevilla requested changes

2024-06-04 18:22 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DND/DNDComponent/UnBlock.tsx
> +        <>
Remove this react fragment.

2024-06-04 18:22 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DND/DND.tsx
> +                                                            if (index % 2 === 0) {
Don't use if condition inside the react render

2024-06-05 12:50 UTC, JMSevilla approved these changes

2024-06-05 12:54 UTC, JezChristian approved these changes

2024-06-05 13:04 UTC, acostales08 approved these changes

2024-06-05 14:46 UTC, merged