@86epghkhy #Added a Mobile Detection Context and Dialog Error
JMSevilla/nclexpower_turbo pull request #68
Opened 2024-06-05 13:22 UTC by be3jaay

2024-06-05 13:27 UTC, DropitupQwerty commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +  const [open, setOpen] = React.useState(false);
Just import the useState

2024-06-05 13:36 UTC, DropitupQwerty commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +      setOpen(true);
I think you can use the return value from isMobile

```
setOpen(isMobile)
```

2024-06-05 13:43 UTC, DropitupQwerty commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +    if (isMobile) {
Base on your condition the setState change when isMobile value was changed. 
you can use isMobile return value in setOpen

```
setOpen(isMobile)
```

2024-06-05 13:48 UTC, JMSevilla requested changes

2024-06-05 13:48 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +export const MobileErrorDialog: React.FC = () => {
Kindly add spacing between your imports and export const.

2024-06-05 13:48 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +          <ErrorMobileScreen>
Change this to `<ErrorMobileScreen />`

2024-06-05 13:48 UTC, JMSevilla commented on apps/simulator/src/components/icons/ErrorMobileScreen.tsx
> +export const ErrorMobileScreen = () => {
Find a way to make this minimalist like the `ErrorFieldIcon`

2024-06-05 13:48 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +
There is too much spacing kindly use prettier

2024-06-05 13:49 UTC, DropitupQwerty commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +          <ErrorMobileScreen>
Try using this 
```
<ErrorMobileScreen/> 

instead of 

<ErrorMobileScreen><ErrorMobileScreen/>
```

2024-06-05 13:51 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +    setOpen(true);
Since your goal is to maintain the modal when the isMobile is true you can remove the entire function handleClose also in your dialog component. In that way you can save some lines of code

2024-06-05 17:58 UTC, DropitupQwerty approved these changes

2024-06-06 08:45 UTC, JMSevilla requested changes

2024-06-06 08:45 UTC, JMSevilla commented on apps/simulator/src/components/Dialog/MobileErrorDialog.tsx
> +  const isMobile = useMobileDetection();
useMobileDetection is being used twice. you can instead remove this and add props to pass the isMobile.

Concept should prevent: DRY

2024-06-06 08:45 UTC, JMSevilla commented on packages/core-library/contexts/MobileDetectionContext.tsx
> +export const useMobileDetection = (): boolean => {
This isn't the proper implementation of using useContext you can check the reference for other context API's

2024-06-06 08:45 UTC, JMSevilla commented on packages/core-library/contexts/MobileDetectionContext.tsx
> +export const useMobileDetection = (): boolean => {
We shouldn't return this code a boolean.

2024-06-06 08:45 UTC, JMSevilla commented on packages/core-library/contexts/MobileDetectionContext.tsx
> +  return context.isMobile;
it should be return useContext(context)

2024-06-06 08:45 UTC, JMSevilla commented on packages/core-library/contexts/MobileDetectionContext.tsx
> +  useEffect(() => {
We can remove the entire implementation of toast message since we already have dialog modal

2024-06-06 08:45 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +  const isMobile = useMobileDetection();
it should be const { isMobile }

2024-06-06 13:19 UTC, JMSevilla requested changes

2024-06-06 13:19 UTC, JMSevilla commented on apps/simulator/src/components/parse-contents.tsx
> +  const { isMobile } = useContext(MobileDetectionContext)
You shouldn't use `useContext` since you have `useMobileDetection`

2024-06-06 18:17 UTC, JMSevilla approved these changes

2024-06-07 00:01 UTC, JezChristian approved these changes

2024-06-07 07:40 UTC, merged