@86epcnkxy #Username & Password Validation & Login Logo
JMSevilla/nclexpower_turbo pull request #70
Opened 2024-06-05 19:09 UTC by JezChristian

2024-06-06 08:36 UTC, JMSevilla requested changes

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginForm.tsx
> +import { Box, Grid, Typography } from '@mui/material'
Rename the folder to LoginFormBlock

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginForm.tsx
> +    control: Control<LoginValidationType>
we don't pass control to render component

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginForm.tsx
> +    handleSubmit: () => void
Your handleSubmit should have a value
`handleSubmit: (values: LoginFormType) => void`
can you also pass `submitLoading: boolean;`

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginForm.tsx
> +import { LoginValidationType } from './validation'
Change it to LoginFormType

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginFormBlock.tsx
> +import { FormProvider, useForm } from 'react-hook-form'
Since we have form contained in LoginForm it should not use this FormProvider

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginFormBlock.tsx
> +    const form = useForm({
react hook form should be inside your LoginForm

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginFormBlock.tsx
> +    const onSubmit = (values: LoginValidationType) => {
change name to handleSubmit

async function handleSubmit

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/LoginFormBlock.tsx
> +export const LoginFormBlock = () => {
You are not passing any parameters from the parse cms

pass this values > id, parameters

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/validation.ts
> +import * as Yup from 'yup'
use lowerCase import * as yup from 'yup'

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/validation.ts
> +    rememberMe: Yup.boolean().default(false)
This isn't being used you can remove this

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginBlock/validation.ts
> +export type LoginValidationType = Yup.InferType<typeof loginSchema>;
Change type name to LoginForm

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/contents/cms/parse-cms.tsx
> +          <LoginFormBlock />
No parameters being passed.

2024-06-06 08:36 UTC, JMSevilla commented on packages/core-library/contents/cms/parse-cms.tsx
> +import { LoginFormBlock } from '../../components/blocks/LoginBlock/LoginFormBlock';
Don't access directly the LoginFormBlock

2024-06-06 18:14 UTC, JMSevilla approved these changes

2024-06-06 18:14 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginFormBlock/LoginForm.tsx
> +                <Button fullWidth onClick={form.handleSubmit(handleSubmit)} variant="contained">Login</Button>
it should be onClick={handleSubmit(onSubmit)}

2024-06-07 08:40 UTC, DropitupQwerty approved these changes

2024-06-07 09:53 UTC, acostales08 approved these changes

2024-06-07 12:52 UTC, merged