@86epe33e0 #Refactored MCQCSQuestionnaire
JMSevilla/nclexpower_turbo pull request #71
Opened 2024-06-09 03:46 UTC by be3jaay

2024-06-09 08:29 UTC, JMSevilla requested changes

2024-06-09 08:29 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/MCQTable/MCQCSBlock.tsx
> +          <MCQCSQuestionnaireBlock questionaire={questionaire} answer={answer} />
@DropitupQwerty Is this normal? block is rendered with another parent block.

2024-06-09 08:29 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/MCQTable/MCQCSBlock.tsx
> +export const MCQCSBlock: React.FC<SsrData> = ({ questionaire, answer }) => {
Where's the useForm setup here?

2024-06-10 08:16 UTC, JMSevilla approved these changes

2024-06-10 13:47 UTC, DropitupQwerty approved these changes

2024-06-10 15:48 UTC, JezChristian approved these changes

2024-06-10 15:49 UTC, merged