@86epea4f8 #Web-Backoffice Footer
JMSevilla/nclexpower_turbo pull request #73
Opened 2024-06-09 15:58 UTC by JezChristian

2024-06-10 08:33 UTC, JMSevilla requested changes

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/Layout.tsx
> +            <FooterBlock tenant={tenant} />
This should not be FooterBlock, all blocks is placed under parse cms

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/LoginFormBlock/LoginFormBlock.tsx
> +import { CmsPage, Parameters } from '../../../types/page'
Where did you use this CmsPage? 

Instead of using Parameters from the types/page

use this `{ key: string; value: string }[];`

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/ReusableFooter/Footer.tsx
> +    // const linkGroups = tenant?.footer?.value?.elements?.linkGroups
remove comments

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/ReusableFooter/Footer.tsx
> +    const linkGroups = [{}, {}, {}, {}]
What is this ? please always follow best practices.

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/ReusableFooter/Footer.tsx
> +export const Footer = ({ tenant }: Props) => {
Why we are passing tenants here? 

you should use React.FC and instead of type Props it should be interface Props

your props should have
1. logo that is optional > type > use NonNullable and another NonNullable inside of it. kindly import CmsTenant and use it to get ['footerLogo'] > ['renditions'] > ['default']
2. linkGroups that is optional that also have 2 NonNullable and inside of those is CmsTenant['footer'] > ['value'] > ['elements']['linkGroups']
3. copyrightText?: string

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/ReusableFooter/Footer.tsx
> +    const footerLogo = tenant?.footerLogo?.url //Unused as of now
no need for this.

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/components/blocks/ReusableFooter/FooterBlock.tsx
> +export const FooterBlock = ({ tenant }: Props) => {
What is the purpose of this block ?

2024-06-10 08:33 UTC, JMSevilla commented on packages/core-library/contents/cms/parse-cms.tsx
> +    const tenantType = (content?.elements?.formKey?.value || content?.type).trim();
What is this ?

2024-06-11 19:04 UTC, JMSevilla approved these changes

2024-06-12 00:32 UTC, acostales08 approved these changes

2024-06-12 14:22 UTC, DropitupQwerty approved these changes

2024-06-12 14:23 UTC, merged