@enhancement/86epj4et2/CS-SATA-Questionaire-Validation
JMSevilla/nclexpower_turbo pull request #74
Opened 2024-06-09 15:59 UTC by acostales08

2024-06-10 08:42 UTC, JMSevilla requested changes

2024-06-10 08:42 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/SATA/SATA.tsx
> +    const { activeTab, setActiveTab, csSataAtom } = rest
Why we are passing setting state? and `...rest` is used directly to the component for best practices for example <Component {...rest} />

2024-06-11 14:38 UTC, JezChristian approved these changes

2024-06-11 15:09 UTC, DropitupQwerty approved these changes

2024-06-11 15:13 UTC, merged