@86ep326hr #Added DND Bowtie Validation
JMSevilla/nclexpower_turbo pull request #75
Opened 2024-06-09 16:56 UTC by DropitupQwerty

- Added DND Bowtie Validation
- Refactor code . Move functions to DNDBowtie.tsx

2024-06-10 08:51 UTC, JMSevilla requested changes

2024-06-10 08:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtie/DNDBowtie.tsx
> +  const removeValue = (id: number, container: string, setState: any) => {
This function can be placed inside the blocks

2024-06-10 08:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtie/DNDBowtie.tsx
> +  const addValue = (value: dndObjectValueProps) => {
This function can be placed inside the blocks

2024-06-10 08:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtie/DNDBowtie.tsx
> +  const dropAnswer = (containerName: string, value: dndObjectValueProps) => {
This function can be placed inside the blocks

2024-06-10 08:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtie/DNDBowtie.tsx
> +  const handleRemove = (containerName: string, item: dndObjectValueProps) => {
This function can be placed inside the blocks

2024-06-10 08:51 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtie/DNDBowtie.tsx
> +                          <DroppableContainer
The <DroppableContainer /> component is repeated multiple times with minor variations. This can lead to redundancy and harder maintenance.

Create a helper function to render the <DroppableContainer /> component.

2024-06-11 15:09 UTC, acostales08 approved these changes

2024-06-11 16:10 UTC, JezChristian approved these changes

2024-06-11 16:11 UTC, merged