@86epjn1wv #Added reusable background info layout
JMSevilla/nclexpower_turbo pull request #81
Opened 2024-06-13 17:17 UTC by be3jaay

2024-06-14 07:51 UTC, DropitupQwerty approved these changes

2024-06-14 07:59 UTC, acostales08 approved these changes

2024-06-14 11:01 UTC, JMSevilla requested changes

2024-06-14 11:01 UTC, JMSevilla commented on apps/simulator/src/components/NotesInfo/NotesInfo.tsx
> +        <NotesComponent questionaire={questionaire} activeTab={activeTab} />
Your code seems using same mapping at the same time?

2024-06-15 07:48 UTC, JMSevilla approved these changes

2024-06-15 09:37 UTC, merged